### ISSUE TITLE
Organism download not working

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#101]
as title, you asked for a ticket to remind you to fix it :)

**Comment by tschaka1904** [comment]
Currently we have a strange way of dealing with the file naming. Sometimes it is the name, sometimes the tax id or sometimes all together. We need to clean up the ftp and do this properly. I'll think of a short term solution.

**Comment by tschaka1904** [comment]
I've created a temp fix or a hack. How ever we want to call it, but it working now.
