### ISSUE TITLE
Search Examplex for complex name & list of ACs

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#102]
Please add:
"nuclear pore"
"Q15554, P54274, Q96AP0"

**Comment by tschaka1904** [comment]
Okay no problem! What about the header-search: 
![screen shot 2017-06-02 at 16 08 38](https://cloud.githubusercontent.com/assets/5269116/26731974/cf394042-47ad-11e7-9df4-fc3175245cfc.png)

It looks quite long.

**Comment by bmeldal** [comment]
good :)
But also on home page as header search not visible for first time user

**Comment by tschaka1904** [comment]
Okay in that case I'll leave it like that.
