### ISSUE TITLE
Visual aid for Basket use

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#104]
In testing, on the details page Diego kept clicking on the basket icon instead of the link in the Header when we asked him to go to it. He didn't see the pop-up in the top-right corner.

Can we grey out the basket when the complex has been added?
See UniProt:
![image](https://cloud.githubusercontent.com/assets/10517124/26745975/22e081ba-47e5-11e7-83c9-2985ffae622e.png)

or
Use a symbol that indicates 'added' in some way?
See UniProt Search Results:
![image](https://cloud.githubusercontent.com/assets/10517124/26745955/0637afb6-47e5-11e7-83f3-41b4d9edc233.png)

See new QuickGO:
![image](https://cloud.githubusercontent.com/assets/10517124/26745900/bfcb811a-47e4-11e7-9b8f-d8d9897434fd.png)

We can also make the number in the header menu clearer?
See UniProt:
![image](https://cloud.githubusercontent.com/assets/10517124/26746015/4609c958-47e5-11e7-97f4-9533b22ce5b1.png)

See new quickGO:
![image](https://cloud.githubusercontent.com/assets/10517124/26745867/8d21a41a-47e4-11e7-908d-45236c27eb94.png)

**Comment by bmeldal** [comment]
Sangya:
Also move the item to the right-most position in the header menus.

**Comment by tschaka1904** [comment]
So I did this: 
![jun-29-2017 10-19-11](https://user-images.githubusercontent.com/5269116/27680739-b1d85f8a-5cb4-11e7-8b0a-444f29757390.gif)

Basically it greys out as soon as you added the element to the basket. Also I've moved the Basket tab to the right end of the tab: 
<img width="1214" alt="screen shot 2017-06-29 at 10 20 58" src="https://user-images.githubusercontent.com/5269116/27680784-e0012d74-5cb4-11e7-94d6-51328d8eb59a.png">

**Comment by tschaka1904** [comment]
@bmeldal 

> Forgot about that ticket... Maybe a tick is more visual than greying it out which might look like it's not functioning. Sorry, I keep thinking up new ideas from day to day...

**Comment by tschaka1904** [comment]
There is also a white background here: 
<img width="452" alt="screen shot 2017-06-29 at 10 40 55" src="https://user-images.githubusercontent.com/5269116/27681510-728a50f6-5cb7-11e7-896c-21157edcc920.png">

**Comment by bmeldal** [comment]
I like the white background for the number in basket.

grey out or add a tick - that's the question :) I'll ping Sangya!

**Comment by tschaka1904** [comment]
If tick, I would ask for a basket with a tick.

**Comment by bmeldal** [comment]
Discussed with Sangya: Can we request button with tick and try that? Then that should be really obvious to the user :)

She also says then we can add the option of unticking = remove from basket on the details page if our application allows that.

May want to play with tick on grey button vs green unticked button :)

**Comment by tschaka1904** [comment]
There is this new form: [Request to add an icon to the EMBL-EBI font sets.](https://docs.google.com/forms/d/e/1FAIpQLSe7_lFbhVdt-AJeGQChjkiab642nDkfKTVoNQRosPAKuBP3_g/viewform?c=0&w=1).

**Comment by bmeldal** [comment]
Who should request it?

**Comment by bmeldal** [comment]
Testing with Roser and Natalie:
Could it be in top header like online shopping pages? - Obviously, we can't add it to the global header but Sangya said it's a common issue with EBI service pages and maybe should be reported to WGC?

Fix for us? Change the whole background of the basket menu tab? And/Or move it to the right side of the page???

**Comment by bmeldal** [comment]
post-mtg thoughts:

- Add an icon to the Basket tab in the header
- Add an animation when a complex is added to the basket (with classic till ka-ching effect?!?)

**Comment by tschaka1904** [comment]
![flash](https://user-images.githubusercontent.com/5269116/28780086-71ad5e1c-75fd-11e7-8444-dd9703855797.gif)

**Comment by tschaka1904** [comment]
Still waiting for icons for Basket button.

**Comment by tschaka1904** [comment]
Is there any more visual feedback needed?

**Comment by bmeldal** [comment]
Are the new buttons available, then?

**Comment by tschaka1904** [comment]
No, the icons haven't been provided yet.

**Comment by bmeldal** [comment]
Closing as the greyed out basket seems to be working.
