### ISSUE TITLE
Evidence line in Header

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#108]
Diego found it hard to find the evidence in the header section of the details page. He actively looked for it.

Can we play again with the chemical flask icon Xav introduced in some early mock-ups? Icon catch the eye better then small text.

**Comment by tschaka1904** [comment]
I'll close this issue for now, but feel free to open it again if you would like to give more feedback.

**Comment by tschaka1904** [comment]
![screen shot 2017-06-14 at 17 29 25](https://user-images.githubusercontent.com/5269116/27143659-0a559b08-5127-11e7-8937-31d49c5282be.png)

**Comment by bmeldal** [comment]
Ok, works for know. Eventually, it would be nice to fill up the flask depending on how much evidence we have:
full flask = experimental evidence ECO:0000353, ECO:0005542, ECO:0005543
half full = inferred by homology: ECO:0005544, ECO:0005546, ECO:0005610
empty = inferred by curator: ECO:0005547

**Comment by tschaka1904** [comment]
We would need to ask for new icons.

**Comment by bmeldal** [comment]
Who should ask, you or me?

**Comment by tschaka1904** [comment]
I've requested it here: [EBI Icon font wishlist](https://github.com/ebiwd/EBI-Icon-fonts/issues/6)

**Comment by tschaka1904** [comment]
Spence has created a two more flasks (empty & full) and once they are released we can use them on our details page.

**Comment by bmeldal** [comment]
Testing: Flask still not visible to users.

Place 'flask' into a green circle, see mock-up on Slack today (post-mtg notes).

@tschaka1904 please re-open
