### ISSUE TITLE
Add complex assembly

### ISSUE THREAD

**Issue by tschaka1904** [Complex-Portal/complex-portal-view#11]

**Comment by bmeldal** [comment]
Should be near viewer or top of <Properties> section

**Comment by tschaka1904** [comment]
Can you provide an example with an assembly?

**Comment by bmeldal** [comment]
Hemoglobin example has it :)

**Comment by tschaka1904** [comment]
> Should be near viewer or top of section

This means into the Function section?

**Comment by bmeldal** [comment]
Yes, at the moment it's the first section of the function before the description. The 2 sections can also be swapped.
@sandraorchard, which order would you prefer?

**Comment by sandraorchard** [comment]
As its related to the Stoichiometry, I would say as near to the Participants Table as you can fit it.

**Comment by bmeldal** [comment]
That would be first sub-section of the 'Function' section then.

**Comment by tschaka1904** [comment]
Okay.

**Comment by bmeldal** [comment]
Still not added, or is it awaiting deployment?

Please re-open, I don't have the button to do so :(

**Comment by tschaka1904** [comment]
I think I stopped it, because it just didn't feel right to put is just there

**Comment by sandraorchard** [comment]
Sorry to be difficult, but it doesn't work where it is, in the middle of the Function information. Can we move it to Properties, to follow the free text statement since we can't get it adjacent to the components table.

**Comment by bmeldal** [comment]
Good idea. At least it's next to the crystal if we have one. 

I guess the only issue is when the crystal is partial or the displayed structure is a smaller proportion of the "real"complex, e.g. 1:1 instead of 2:2.

**Comment by bmeldal** [comment]
Shouldn't the header be "Assembly" (rather than "Assemblies") as we only have one per entry (with maybe one or two exceptions)?

**Comment by bmeldal** [comment]
@tschaka1904 please correct to "Assembly" and also increase space above header, it looks all squished again.

Can't reopen - no button...
