### ISSUE TITLE
Reactome widget not working in IE11

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#111]
Antonio and Kostas fixed it on their end (rolling back to the green boxes) but the widget doesn't show up at all in the CP.

Antonio's email to me (as reference):

Hi Birgit,

After some investigation, Kostas and I found that the reason why it doesn't work is because IE11 doesn't support SVG inline CSS (a feature we rely on).

As a workaround agreed with Henning is to show the former green boxes diagrams as a fallback. If the users wish to enjoy our new text-book style diagrams, we encourage them to use any other browser.

Could you please check it out and let us know whether it works? The changes should be already available without any action needed from your developers ;)

Best regards,

--
Antonio Fabregat Mundo

**Comment by tschaka1904** [comment]
I've double checked the issue and this issue is now down to us. I'll need to add some [Pollyfills](https://stackoverflow.com/questions/7087331/what-is-the-meaning-of-polyfills-in-html5) to be compliant with that browser.

**Comment by bmeldal** [comment]
Closing it as user hasn't come back to complain. They use an ancient version anyway...
