### ISSUE TITLE
Ontologies, Citation, 3D Structures link, Organsims icon, Uni(P)portKB, evidence link

### ISSUE THREAD

**Issue by magrane** [Complex-Portal/complex-portal-view#112]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search existing issues for a similar problems/requests
[ ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

As requested by Sandra, I played around with the new site and found a few things:

- The 'Ontologies' and 'Citation' buttons on the home page doesn't seem to do anything.

- On the Organisms page (http://www.ebi.ac.uk/complexportal/complex/organisms), there's a big X over Pseudomonas aeruginosa. Is that because you have no picture for this? Looks a bit odd.

- For entries with 3D structures, the linking is confusing. I clicked on the PDB code first before trying the icon.

- When I click on the evidence for the complex at the top of the page, it goes to the OLS home page rather than to the specific term e.g. clicking on 'physical interaction evidence' at the top of this page: http://www.ebi.ac.uk/complexportal/complex/EBI-10099500 goes here: http://www.ebi.ac.uk/ols/index.

- In the pulldown menu in the 'Participants' section, UniprotKB should be changed to UniProtKB.

**Please tell us about your environment:**
 Chrome 58.0.3029.110 (64-bit)

**Comment by bmeldal** [comment]
Hi Michelle,

Thank you for having a play. I can answer most items directly:

"Ontologies" & "Citations": still under development. Do you think it would make sense to add a traffic cone symbol on the tile while it has no function?

Pseudomonas: I guess that's a CSS issue as it did have a picture last time I looked at it and I just checked a screenshot where it is displayed. @tschaka1904 will check it :)

3D structures: yes, we are still playing around with the best layout for the links. Would you prefer a more wordy column header, something like "View structure in LiteMol" and "View structure in PDBe"?

Evidence: That's a bug. OLS changed the search url again and it will be updated with the next release.

"UniprotKB" in the viewer menu: @tschaka1904, does that come from Colin's code?

**Comment by tschaka1904** [comment]
> "Ontologies" & "Citations": still under development. Do you think it would make sense to add a traffic cone symbol on the tile while it has no function?

I'll add a notification. Like I do for the 'enlarge'-button at the complexviewer.

> Pseudomonas: I guess that's a CSS issue as it did have a picture last time I looked at it and I just checked a screenshot where it is displayed. @tschaka1904 will check it :)

For some reason the name of the organisms has changed(?) I'll update the code.

> "UniprotKB" in the viewer menu: @tschaka1904, does that come from Colin's code?

Nope this comes from our side

**Comment by bmeldal** [comment]
@magrane 

>    "Ontologies" & "Citations": still under development. Do you think it would make sense to add a traffic cone symbol on the tile while it has no function?
>I'll add a notification. Like I do for the 'enlarge'-button at the complexviewer.

Michelle, did you see the notifications in the top right corner?

**Comment by tschaka1904** [comment]
I've linked existing issues or created new once and linked them to this issue. .

**Comment by tschaka1904** [comment]
I'll close this issue, as most of the named issues are solved and are going to go live tomorrow. Issue #80, will be solved as soon as we have an answer from the OLS guys.
