### ISSUE TITLE
Organsims icon not displayed

### ISSUE THREAD

**Issue by tschaka1904** [Complex-Portal/complex-portal-view#114]
It seems that the name of an organisms has been changed and we need to update the code to display the right icon again. 

This was mentioned in #112

**Comment by sandraorchard** [comment]
Also spacing of the 2 fish at the end looks a bit odd, they seem to be stacked rather than side-by-side.

**Comment by bmeldal** [comment]
Yes, I noticed that. Something got shifted...

**Comment by tschaka1904** [comment]
Displayed name is still to long.

**Comment by tschaka1904** [comment]
![screen shot 2017-06-14 at 17 25 28](https://user-images.githubusercontent.com/5269116/27143503-7a375b6a-5126-11e7-9e7b-01a46dbd56e9.png)

**Comment by bmeldal** [comment]
Are we able to manipulate the way the name is displayed? If so, use
"Pseudomonas aeruginosa (strain ATCC 15692)"

**Comment by tschaka1904** [comment]
We're able to, but this is something which should be handled by the WS and not by the view. The organisms view is tweaked a lot to make it work with the current WS. But I can truncate for the time being.

**Comment by bmeldal** [comment]
If you are happy to truncate manually for now until we have the new WS go ahead.
