### ISSUE TITLE
Disappearing synonyms

### ISSUE THREAD

**Issue by sandraorchard** [Complex-Portal/complex-portal-view#117]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search existing issues for a similar problems/requests

All the synonyms have disappeared. 
Also suggest we swap them round so Systematic name (which we always have) is on the left, and Synonyms (which we may not) is on the right.

**Please tell us about your environment:**
<!-- Windows  Firefox 
Sandra

**Comment by tschaka1904** [comment]
Synonyms are bag, but placeholder displays `Synonyms (0)`, if no Synonyms. It should not be there at all.

**Comment by tschaka1904** [comment]
![screen shot 2017-06-14 at 17 26 52](https://user-images.githubusercontent.com/5269116/27143559-acc9a308-5126-11e7-8815-545fdd00d470.png)

**Comment by bmeldal** [comment]
Bug is back:
http://www.ebi.ac.uk/complexportal/complex/EBI-10887677

Can't reopen ticket :(
