### ISSUE TITLE
LiteMol not working

### ISSUE THREAD

**Issue by sandraorchard** [Complex-Portal/complex-portal-view#118]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search existing issues for a similar problems/requests
[ ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```
LiteMol viewer did not load with default structure. Also did not work when I pressed a link.

**Current behaviour**

**Expected behaviour**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behaviour?**

**Please tell us about your environment:**

**Comment by sandraorchard** [comment]
Further update.. Working fine when I opened http://www.ebi.ac.uk/complexportal/complex/EBI-11665196

Still not working when I opened 
http://www.ebi.ac.uk/complexportal/complex/EBI-9992716

**Comment by tschaka1904** [comment]
Okay, it works for me in both cases. Are you using Internet Explorer 11?

**Comment by tschaka1904** [comment]
XRef is obsolete and that is why it is not showing the viewer. But there is another issue, which is the unstable order of the XRefs. This issue will be closed, but the XRefs order issue will be tracked at: #120
