### ISSUE TITLE
FtIDs and expression data. 

### ISSUE THREAD

**Issue by sandraorchard** [Complex-Portal/complex-portal-view#119]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search existing issues for a similar problems/requests
[ X] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

Atlas does not work for those proteins where a FtID has been used e.g. EBI-11665196 
 IL23A  
Q9NPF7-PRO_0000259488. Can it be told to search on the canonical ID Q9NPF7

**Comment by bmeldal** [comment]
Moved to Jira:
https://intact.atlassian.net/browse/CP-238
