### ISSUE TITLE
Order XRefs by alphabet

### ISSUE THREAD

**Issue by tschaka1904** [Complex-Portal/complex-portal-view#120]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search existing issues for a similar problems/requests
[x] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**

Currently we pull in most XRefs and display them as they are coming, but it might be a good idea to order them.
**Expected behaviour**

XRefs order by alphabet.
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behaviour?**

Tabels will look equal for everyone.
**Please tell us about your environment:**

**Comment by tschaka1904** [comment]
This is maybe something which can be taken care of by the new WS?

**Comment by bmeldal** [comment]
Moved to Jira:
https://intact.atlassian.net/browse/CP-238
