### ISSUE TITLE
G0-to menu only allows user to jump upwards on mobile 

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#121]
Tested by Birgit and Noe on Chrome for Android. Only displays current section and those above and does not react to clicking on it.

Max already knows where the bug comes from :)

**Comment by tschaka1904** [comment]
Please a be little more a descriptive with titles of a ticket, otherwise we will have 3 'Go To menu'-issues.

**Comment by tschaka1904** [comment]
Based on the stats, I wouldn't invest so much into it. Maybe there is a nicer way to implement a [menu like QuickGo](https://foundation.zurb.com/sites/docs/magellan.html) has.

**Comment by bmeldal** [comment]
Yes, Xav is looking at re-designing the navigation.
