### ISSUE TITLE
RNA symbol lost in legend

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#122]
See: 
http://www.ebi.ac.uk/complexportal/complex/EBI-9997373
![image](https://user-images.githubusercontent.com/10517124/27127030-663afbba-50f1-11e7-82a0-2b0b71a47bce.png)

**Comment by tschaka1904** [comment]
![screen shot 2017-06-14 at 17 27 27](https://user-images.githubusercontent.com/5269116/27143601-ccdb66a4-5126-11e7-9ee1-a7a52ca5a65e.png)

**Comment by bmeldal** [comment]
Thanks :)

**Comment by tschaka1904** [comment]
@bmeldal please add list of RNAs

**Comment by bmeldal** [comment]
We have:
RNAs:
small nuclear rna - no symbol
small nucleolar rna - no symbol
transfer rna - no symbol
signal recognition particle rna - no symbol
ribonucleic acid - with symbol

DNAs:
double stranded deoxyribonucleic acid - no symbol
single stranded deoxyribonucleic acid - with symbol

**Comment by bmeldal** [comment]
Looks fixed.
