### ISSUE TITLE
Twitter account @complexportal

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#125]
[ ] bug report => search existing issues for a similar problems/requests
[x ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact

**Current behaviour**
Currently, we only tweet from @intact_project but with the new website and url we though it might be an idea to give the CP it's own Twitter identity, too.

**Expected behaviour**
@ complex exists - some sort of pop culture magazine, >1Mill followers!
could use
@ complexportal
@ ebi_complex
@ ebi_complexportal

**Comment by tschaka1904** [comment]
Done! [@complexportal](https://twitter.com/complexportal)
