### ISSUE TITLE
Publication page

### ISSUE THREAD

**Issue by tschaka1904** [Complex-Portal/complex-portal-view#128]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search existing issues for a similar problems/requests
[X] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**

Currently we show a modal, as described in issue #113.

**Expected behaviour**

As from @bmeldal described and discussed in issue #113 , we would like to create a new page for publication. Current plans are to move to the `About`-page and link from the citation modal there as well.
cc: @sandraorchard @bmeldal

**Comment by tschaka1904** [comment]
We need a mock up for this.

**Comment by bmeldal** [comment]
Can I do a pen+paper one?

**Comment by tschaka1904** [comment]
Yes sure, afterwards just scan it and put it here ;-)

**Comment by bmeldal** [comment]
![publication_page_mockup](https://user-images.githubusercontent.com/10517124/28418516-e56ee634-6d53-11e7-8340-5f6ab45f0dc1.jpg)

**Comment by bmeldal** [comment]
Do we want to manually select the publication to display or can we employ some sort of search algorithm in EPMC that at least updates the 2nd and 3rd section?

**Comment by sandraorchard** [comment]
How many are you planing on writing?

**Comment by bmeldal** [comment]
The third section should include related articles but probably tricky to create a search string for that so better to decide on a list and update when needed...

Writing 2 this year, book chapter and NAR paper, right? Allocation on mock-up isn't particularly precise! Once the 2018 paper is out it'll replace the 2015 paper in the 'how to cite us' section and the 2015 paper drops down.

**Comment by bmeldal** [comment]
Oh, and the three paper we are writing for the Midas grant need to be added to section 2 once out... It'll become a nice list!

**Comment by bmeldal** [comment]
Also see: https://intact.atlassian.net/projects/CP/issues/CP-18

We need to add a section to acknowledge funding. Near publications or completely separate issue?

**Comment by bmeldal** [comment]
Moved to Jira:
https://intact.atlassian.net/browse/CP-236
