### ISSUE TITLE
Custom form for 'Request Complex for Curation'

### ISSUE THREAD

**Issue by tschaka1904** [Complex-Portal/complex-portal-view#129]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search existing issues for a similar problems/requests
[X] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```
We've go the initial script from www-dev to create custom submission forms. @bmeldal could you please share your form with me, so I can implement it?

**Comment by bmeldal** [comment]
template is here:
https://docs.google.com/document/d/1Tip6hIWg1hIkR0zcjx3zwODTtUzGRuL3DTKhfqquwHc/edit?usp=sharing

Sorry, it slipped through backlog...

**Comment by sandraorchard** [comment]
Too complicated - reserve that for mailing out to professional curators who send you a list. Ask for a name, species and a paper in the basic form.

**Comment by bmeldal** [comment]
Maybe also UniProt IDs if they have them already. Sometimes it's not obvious immediately.

**Comment by tschaka1904** [comment]
This needs some work on the WS as well, as I can't send emails via JavaScript. 
/cc @git4anjali @noedelta

**Comment by bmeldal** [comment]
Also Jira ticket: https://intact.atlassian.net/projects/CP/issues/CP-50

**Comment by bmeldal** [comment]
I was thinking, why are we trying to shoehorn something into an RT request that should be a GH tracker? It works well for GO. It means I only have one place where I have to keep track of requests (currently its in Jira but I have to copy requests from emails as external user have no access so it creates 2 places where I have to keep track). On GH our users can use it directly, keep track and answer questions. If users can manage GO request via GH they should be able to manage CP requests.

**Comment by tschaka1904** [comment]
Here we go! The issue was that someone needs to send an email and I can not do that from the client. 

/cc @git4anjali @noedelta

**Comment by bmeldal** [comment]
using RT for now
