### ISSUE TITLE
Implement Twitter summary card

### ISSUE THREAD

**Issue by tschaka1904** [Complex-Portal/complex-portal-view#130]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search existing issues for a similar problems/requests
[X] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**

Currently when we share the link on twitter it will just look like this: 
![screen shot 2017-06-16 at 11 54 05](https://user-images.githubusercontent.com/5269116/27223937-92f8b1ac-528a-11e7-9d87-d10bc9c78aba.png)

**Expected behaviour**

Using the summary card, we could do something more like this: 
[
![screen shot 2017-06-16 at 11 54 43](https://user-images.githubusercontent.com/5269116/27223998-d99052d2-528a-11e7-89e0-25c7963624be.png)
](https://dev.twitter.com/cards/types/summary)

**What is the motivation / use case for changing the behaviour?**

A bigger and more impressive look of our tweets.

###### Just a few guidelines for how to write effective and good GitHub issues: [HOW WE WRITE GITHUB ISSUES](https://wiredcraft.com/blog/how-we-write-our-github-issues/)

**Comment by bmeldal** [comment]
Closing as I don't think we'll do much about this anytime soon. Unless we get another super-keen tweeter ;-)
