### ISSUE TITLE
 gamma secretase request

### ISSUE THREAD

**Issue by cdsouthan** [Complex-Portal/complex-portal-view#132]
PSEN1 is in the gamma secretase complex with a crucial role in Alzheimer's.  I can't find it even with "presenilin" or "secretase"

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search existing issues for a similar problems/requests
[x ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**

**Expected behaviour**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behaviour?**

**Please tell us about your environment:**

**Comment by bmeldal** [comment]
Thanks, Christopher.
This complex is already on my to do list but I'll prioritise it as much as I can!

**Comment by bmeldal** [comment]
To make it faster for me to curate, have you got any of the following info:

PMIDs for interaction/structural data
PMIDs describing the specific function of the complex

Any other info that you feel must go in the description?

**Comment by tschaka1904** [comment]
I'll close this issue as this is a curation request and no development task.
