### ISSUE TITLE
Selectable cross references 

### ISSUE THREAD

**Issue by cdsouthan** [Complex-Portal/complex-portal-view#133]
Do you have x-refs in UniProt ? i.e. "this protein is in a complex"

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search existing issues for a similar problems/requests
[ x] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**

**Expected behaviour**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behaviour?**

**Please tell us about your environment:**

**Comment by bmeldal** [comment]
Hi Christopher,

We are in talks with UniProt about how exactly we are going to integrate complex ACs into the UniProt pages. It's something we are hoping to achieve this year!

Birgit

**Comment by bmeldal** [comment]
Done a while ago, just forgot to close ticket.
