### ISSUE TITLE
Intro on homepage - not specific enough for first-time user?

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#134]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search existing issues for a similar problems/requests
[x] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**
"The Complex Portal is a manually curated, encyclopaedic resource of macromolecular complexes from a number of key model organisms. All data is freely available for search and download. To perform a search for macromolecular complexes use the search box below."

**Expected behaviour**
Some people find it hard to intuitively understand what the CP contains or how it differs from UniProt.
We may need to list the types of molecules, something like this:
"The Complex Portal is a manually curated, encyclopaedic resource of macromolecular complexes from a number of key model organisms. **The majority of complexes are made up of proteins but may also include nucleic acids or small molecules.** All data is freely available for search and download. To perform a search for macromolecular complexes use the search box below. Read more here [hyperlink to About page]."

**What is the motivation / use case for changing the behaviour?**
To make it clear what molecules are in a complex.

**Comment by tschaka1904** [comment]
Is '**The majority of complexes are made up of proteins but may also include nucleic acids or small molecules.**' also supposed to be bold on the homepage?

**Comment by tschaka1904** [comment]
![screen shot 2017-06-23 at 16 36 05](https://user-images.githubusercontent.com/5269116/27489352-2086f518-5832-11e7-930c-996bc9643b57.png)

**Comment by bmeldal** [comment]
I'm happy with it.
@sandraorchard ?

**Comment by sandraorchard** [comment]
OK with me
