### ISSUE TITLE
Viewer buttons too "strong"

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#135]
The 4 buttons for manipulating the viewer are very obvious leading our users during testing to believe those actions are for the whole page. Sangya suggested we could make them in a grey-scale rather than using the dark green background. Cf UniProt's FeatureViewer.

(and yes, I know you can't export metadata in svg but apparently that's not obvious to naive users...)

**Comment by tschaka1904** [comment]
How about this: 
![screen shot 2017-06-23 at 10 00 18](https://user-images.githubusercontent.com/5269116/27474801-f372fa68-57fa-11e7-9015-2193ee17d600.png)

**Comment by bmeldal** [comment]
Perfect :)
