### ISSUE TITLE
Reactome table - needs buttons, not links

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#136]
1. 
Currently, the Complex and Pathways ACs are hyperlinks that activate a change into diagram focus. However, what we are actually doing is not linking out to somewhere but asking for an action on the same page. Sangya and I think we should make these buttons, then the user will expect a change in the vicinity of the button. The headers of the table should maybe also say "Choose complex" and "Choose pathway" to make it clearer it's an action!

2. 
On a laptop screen the diagram is not visible if there is a list of complex/pathway IDs from Reactome. Maybe the button should say "View in diagram below" to point the user into the right direction.

3.
The second part to the table we provide with the linkouts to Reactome should probably go below the diagram. Then the user has a better change to see that diagram below the table and as they explore the diagram they can then find the linkouts. 

4.
I think the spacing in both tables could be slightly reduced to gain some screen space.

**Comment by tschaka1904** [comment]
The buttons are not a problem. 👍 For the other three points I would say that we need to properly rethink the structure and the layout of this section, I've the feeling that this is not solving the issue of the spacing also relating to #99.

**Comment by bmeldal** [comment]
Ok, start with the buttons and use same design as for the viewer.

If we can move the second table below the diagram for the next tests that would at least give us some feedback on whether it makes any difference.

**Comment by tschaka1904** [comment]
![screen shot 2017-06-23 at 15 32 48](https://user-images.githubusercontent.com/5269116/27486681-46abfcce-5829-11e7-8f3c-661e491ea902.png)

I don't think that this looks good. 

/cc @noedelta @sandraorchard

**Comment by bmeldal** [comment]
What about a fainter grey background?

**Comment by tschaka1904** [comment]
So we have this as a global layout for tables and we would need to change them all or make the Pathways-table not a table.

**Comment by bmeldal** [comment]
I sent the link to this ticket to Sangya for comment. It's a tricky one to get right.

I also just realised that we should use the same patters for the LiteMol viewer as clicking on the AC changes the displayed structure :)

**Comment by bmeldal** [comment]
Re: LiteMol:

Using buttons would also resolve the following issue:
A user thought the second of three ACs (Hemoglobin!) was displayed as that one has the dark background in the table. Do you want a separate ticket for this issue? It would be resolved if we moved to buttons as discussed above.

**Comment by tschaka1904** [comment]
Let's first have meeting the Xav and/or Sangya to find a cleaner way to display this. Changing buttons doesn't solve the main issue of interacting between table/data and diagram.

**Comment by bmeldal** [comment]
Will be part of Tuesday's discussion.

**Comment by bmeldal** [comment]
From meeting on 4/7/17:

We'll try and use dropdown menu as that will solve the issue of indicating which complex and pathway have been selected and it will save a lot of space.

Problem: how to square the issue of many complexes and many pathways overlapping.

**Comment by bmeldal** [comment]
Added to Jira:
https://intact.atlassian.net/browse/CP-231
