### ISSUE TITLE
Links open in new window/tab - leads to gazillions of open windows/tabs

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#137]
I originally requested that external links open in a new window/tab fearing that people close the window and loose the complex site. However, now we end up with lots of open windows/tabs which starts to irritate users. UniProt stay in the same window. 

I can see the merit of staying in the same window. Users can manually choose to open a new window/tab.

**Comment by tschaka1904** [comment]
This is a very controversial problem. Here I found a interesting article about that: [should i open external links in new tab](http://thinksem.com/blog/should-i-open-external-links-in-new-tab/).

**Comment by bmeldal** [comment]
Thanks, interesting article and supports our initial gut feeling of newTab :)

**Comment by bmeldal** [comment]
Moved to Jira:
https://intact.atlassian.net/browse/CP-234
