### ISSUE TITLE
GO-to menu is missing ‘back to top’

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#138]
The highest level of the GO-to menu is currently "Participants", not the top of the page.

**Comment by tschaka1904** [comment]
That should be a own little thingy on the bottom of the page, as 'Back to top' is not a category. Something like this: [http://www.menucool.com/ui/back-to-top-arrow](http://www.menucool.com/ui/back-to-top-arrow) (scroll and look in the lower right side corner)

**Comment by bmeldal** [comment]
We could try that. In UniProt they use "Top" below the navigation pane.

**Comment by tschaka1904** [comment]
I've requested an icon to build this feature, as there are currently no arrow pointing to the top.

**Comment by bmeldal** [comment]
Moved to Jira:
https://intact.atlassian.net/browse/CP-233
