### ISSUE TITLE
"Further Reading" - unclear where refs come from

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#139]
It is currently not clear where these refs come from and what they are related to. Initially we only added reviews of functional papers but I have started to quote the experimental origins and GO papers as there is nowhere else on the page where we can link to these. 

Sangya suggested to call the "Curated references" to at least say that they are manually picked and not electronically inferred.

In the longterm it would be brilliant if we could link them to the right section, like UniProt do now but I know this needs a massive change to the Editor :( (or maybe just a specific qualifier that identifies the section???)

//cc @sandraorchard @noedelta @git4anjali

**Comment by sandraorchard** [comment]
I would NOT add all the GO references - just those with key information in. The GO references are separately captured, and displaying those next to the GO term (UniProt-style?) would be a better option for those.

**Comment by bmeldal** [comment]
Yes, I would like to display the PMID for GO terms next to the terms but was so far voted down on the idea (not priority). Also would like to do same for crystals, EM structures and the IntAct interaction evidence xref. But in the Editor we have only got the option for GO so far. We should enable the ref & ECO fields in xrefs for more DB types. Won't help with old complexes but at least we could start doing it properly for new ones.

**Comment by sandraorchard** [comment]
Can we use PDB/EMDB/IntAct WS to pull them down. - if we have the ACs, why do redundant curation?

**Comment by bmeldal** [comment]
Yes, I forgot about WS...

**Comment by tschaka1904** [comment]
Isn't this a duplicate of #45?

**Comment by bmeldal** [comment]
Yes, sorry. Short-term memory loss...

**Comment by bmeldal** [comment]
Moved to Jira:
https://intact.atlassian.net/browse/CP-17
