### ISSUE TITLE
Add menu to navigate through details page

### ISSUE THREAD

**Issue by tschaka1904** [Complex-Portal/complex-portal-view#14]
We want to have a floating menu on the details page. Similar to UniProt.

**Comment by tschaka1904** [comment]
This is apparently not as strength forward as I thought. We face several problem. One is that the 'Sticky' element of Foundation can't deal with dynamic pages. This is a issue I can solve, I just need to reInit the widget. The bigger problem is, and I don't know why this is happening, that the 'Sticky' element has problems with being initialised without a full-page-request. I don't know why. Since this is eating up to much time currently, I'll revisit this issue later.

**Comment by bmeldal** [comment]
Anyone else at EBI using that technology who you could ask? Is there an all-ebi-dev list of some sort? I take it Uniprot are using a different technology?
(sorry, I can't give you an actual solution).

**Comment by tschaka1904** [comment]
Foundation is just not the best choice for dynamic content. Or at least some features are not. I was talking to people at Pfam and they use React. React is a technology from Facebook and has a similar approach to what we're doing. I asked them about their solution and they said that they have a designer and don't even bother with EBIs Foundation. We are currently the first team using this technology (Angular2), but there is a lot of interest at the EBI to use it.

**Comment by bmeldal** [comment]
Personally, I don't care what's underneath the hood as long as it works ;-)
I'd be happy for you to go off and explore the technology that actually serves our use case.

**Comment by tschaka1904** [comment]
It will just have to wait until I've more time to spend on this. Otherwise it will put the whole project on hold.

**Comment by bmeldal** [comment]
Alternative thought (from yesterday):
We could use the "jump to menu" option. This is often used by journals to navigate between sections in the html view.

**Comment by bmeldal** [comment]
Mark Bingley has developed the navigation bar for the new QuickGO page. It's on the right hand side, though.

**Comment by tschaka1904** [comment]
I'm aware of that. I used that as an example with Xav.

**Comment by bmeldal** [comment]
Sorry, I wasn't in the picture... Sangya mentioned it.

**Comment by tschaka1904** [comment]
New version of complex portal has now a menu on each section. This menu indicates at which section you're and which other sections are available. Clicking on a section will activate a scroll event and brings you to this section: 
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/5269116/26007196/5dc81cfc-3737-11e7-8bd3-5f340ac6355d.gif)


We agreed against a QuickGo like menu, because it would take quite a lot of space. This approach basically follows the practice of some journals, as you can see here: 
<img width="916" alt="screen shot 2017-05-12 at 17 27 50" src="https://cloud.githubusercontent.com/assets/5269116/26007487/96d6cfce-3738-11e7-86e5-be954f4c4e6e.png">
