### ISSUE TITLE
linking from viewer edge to experimental data

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#140]
Ok, this is a bit of a placeholder here as it's really a ticket for the viewer but we need to discuss it in the context of the CP design, too.

When we, eventually, are able to link from the binary edge in ComplexViewer to the experimental evidence via our new WS, would we be able to also link to PDBe and EMDB evidence? It would be a little like the way Reactome handles Interaction evidences from multiple PSICQUIC services.

One to discuss with Saqib, too.

**Comment by tschaka1904** [comment]
I guess, this is a discussion where Colin also needs to be involved?

**Comment by bmeldal** [comment]
Absolutely. And it's not a short-term issue but I didn't want to forget about it!

@colin-combe

**Comment by bmeldal** [comment]
Moved to Jira and linked to related issues:
https://intact.atlassian.net/browse/CP-232
