### ISSUE TITLE
Basket/save/download buttons

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#141]
Currently, the users don't spot the icons very well. Alternatively, we could try and use green buttons with the text written on it.

**Comment by bmeldal** [comment]
You already use a green button to delete a complex from the basket list!

**Comment by tschaka1904** [comment]
There is an issue with the icons and the size of the buttons. I've reported it here: [EBI-Icon-fonts#14](https://github.com/ebiwd/EBI-Icon-fonts/issues/14)

**Comment by tschaka1904** [comment]
I've integrated this new modal view: 
![jun-28-2017 16-11-41](https://user-images.githubusercontent.com/5269116/27644914-ac541498-5c1c-11e7-8f9e-8e33b75fe646.gif)

For now I'm only able to allow JSON as an download option (issue with the naming of files on FTP), but it should show the user what we're able to offer as an download. 

//cc @sandraorchard

**Comment by tschaka1904** [comment]
Also this here: 
![screen shot 2017-06-28 at 16 26 32](https://user-images.githubusercontent.com/5269116/27645706-a8c71b02-5c1e-11e7-9e21-6f09dcd3bbe0.png)

**Comment by tschaka1904** [comment]
Or in grey: 
![screen shot 2017-06-28 at 16 28 02](https://user-images.githubusercontent.com/5269116/27645744-ca3d5850-5c1e-11e7-893c-7a8620001a4d.png)

**Comment by bmeldal** [comment]
I prefer the green here as it's a global action. Then reserve grey buttons for actions within a widget.

However, tiles on the home page and download page bring up a new window or popup. Here, the download icon will bring a popup but the basket is a nearly invisible action. So, if we go by function, the two should look slightly different but definitely more button-y.

The basket icon also needs a 'tick' or '+' to show the user it did something, esp when you come back to the same entry and you have forgotten if you saved it already...

**Comment by tschaka1904** [comment]
```
However, tiles on the home page and download page bring up a new window or popup. Here, the download icon will bring a popup but the basket is a nearly invisible action. So, if we go by function, the two should look slightly different but definitely more button-y.

The basket icon also needs a 'tick' or '+' to show the user it did something, esp when you come back to the same entry and you have forgotten if you saved it already...
```

#104

**Comment by bmeldal** [comment]
Forgot about that ticket... Maybe a tick is more visual than greying it out which might look like it's not functioning. Sorry, I keep thinking up new ideas from day to day...

**Comment by tschaka1904** [comment]
This is what Xav is suggesting: 
![complex-portal](https://user-images.githubusercontent.com/5269116/27876793-39318542-61b0-11e7-9504-7b1255e117f4.png)

**Comment by sandraorchard** [comment]
OK, yes that looks a lot more obvious.

**Comment by bmeldal** [comment]
Are we going for the blue or stick with green as all other features on the page?
