### ISSUE TITLE
Table in line with CP viewer?

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#144]
Just a suggestion for a simple layout tweak: If the table header was at the same level as the the top of the diagram it might be more obvious to users that the two go together. I know, in principle the header for the table is in line with the 'header' for the viewer, e.i. the buttons, but somehow to the eye it doesn't look aligned. 

Suggestion: move buttons and menu below viewer? That was also the suggestion from another user last week.

**Comment by tschaka1904** [comment]
I guess you say diagram, but mean the CP viewer?

**Comment by bmeldal** [comment]
Yes, the diagram that is the Viewer without the menu and buttons!

**Comment by tschaka1904** [comment]
The wording of diagram and viewer is a bit confusing.

**Comment by bmeldal** [comment]
Ok, I'll stick to CP Viewer!

**Comment by tschaka1904** [comment]
![screen shot 2017-06-27 at 17 01 40](https://user-images.githubusercontent.com/5269116/27597477-528eca38-5b5a-11e7-8d3b-2c033e9385d1.png)

**Comment by bmeldal** [comment]
Let's try and test this with the last 1 or 2 people. I will also email Jo and David for their opinion once you deployed.
