### ISSUE TITLE
Common name for organisms?

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#145]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search existing issues for a similar problems/requests
[x ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**
only displays scientific name

**Expected behaviour**
could add 'common name'

**Minimal reproduction of the problem with instructions**
not a problem 

**What is the motivation / use case for changing the behaviour?**
for less well know species the scientific name is not very clear - although we have the icon but that's fairly generic
Issues: 
We don't need to add names like human, mouse, rat, and all the MODs as people are very aware of these!
How would we tell the WS where to add the common name and where to leave it to just the scientific name???

**Comment by tschaka1904** [comment]
I guess, you will either have to define a new field `common_name` in the editor or we have to go with one, the other or both. Or maybe just the common name for the search/filter?

**Comment by tschaka1904** [comment]
Why don't we just do for all filters the same way how 'Dog' is displayed? 
![screen shot 2017-06-30 at 13 55 40](https://user-images.githubusercontent.com/5269116/27736548-81095cae-5d9c-11e7-85c1-02299dede3dc.png)

**Comment by bmeldal** [comment]
Doesn't work for bugs that have no common name but need strain IDs!

**Comment by bmeldal** [comment]
We had no user complaints and this issue is not really easy to resolve so closing it for now.
