### ISSUE TITLE
New filter for evidence

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#146]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search existing issues for a similar problems/requests
[x ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**
need to know the codes from Documentation, then do generic search

**Expected behaviour**
Add a new filter topic for Evidence

**Minimal reproduction of the problem with instructions**
NA

**What is the motivation / use case for changing the behaviour?**
Users would like to filter by experimentally-proven entries only but wouldn't know where to find the codes unless we tell them. Need to provide more context-dependent help (#93) and a filter.

**Please tell us about your environment:**
NA

**Comment by tschaka1904** [comment]
I can't provide the filters at the moment, as this is a matter or changing the search. But we could try to display the evidence for each search result on the results page. ..for now.

**Comment by bmeldal** [comment]
I know, it's a bigger change. 
Yes, could add evidence to search results.
Also need more context-dep help for this #93

**Comment by bmeldal** [comment]
Moved to existing Jira:
https://intact.atlassian.net/browse/CP-46
