### ISSUE TITLE
Citation tile needs rewording

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#147]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search existing issues for a similar problems/requests
[x ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**
Citation

**Expected behaviour**
How to cite us

**Minimal reproduction of the problem with instructions**
NA

**What is the motivation / use case for changing the behaviour?**
Quite a few users expect a list of evidence papers for the curation of the entries behind the "Citation" tile, essentially they expect a bibliography of all papers we used.

**Please tell us about your environment:**
NA

**Comment by tschaka1904** [comment]
![screen shot 2017-06-27 at 16 58 35](https://user-images.githubusercontent.com/5269116/27597298-e0eb39ac-5b59-11e7-9bb1-a74b70a11315.png)
