### ISSUE TITLE
Rectome widget: open in reactome not obvious

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#148]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search existing issues for a similar problems/requests
[x ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**
Need to use link in table or click on Reactome Logo

**Expected behaviour**
Don't know yet but neither current options work

**Minimal reproduction of the problem with instructions**
NA

**What is the motivation / use case for changing the behaviour?**
Users can't see how to open the diagram in Reactome itself. Yesterday, they didn't even look at the table at all, just scrolled through the Reactome diagram (and spent quiet a lot of time looking at that data! It's a favourite!)

**Please tell us about your environment:**
NA

**Comment by tschaka1904** [comment]
This is more a UI issue for reactome, I guess.

**Comment by bmeldal** [comment]
Yes and no, I'm going to send them feedback, too! There was more for them :)

**Comment by tschaka1904** [comment]
It should be obvious in the place where it already is and we shouldn't create redundancy of functionality.

**Comment by bmeldal** [comment]
There's redundancy and they don't see either option! Design has failed :( - back to drawing board.

**Comment by tschaka1904** [comment]
> There's redundancy and they don't see either option!

There is only one option currently to go the the diagram in Reactome. 

The other two links will bring you not to the diagram, but to the actual entry in Reactome.

**Comment by bmeldal** [comment]
ah, yes, may roads lead to Rome...
But they still don't really see any of these links immediately. Even if they saw the link to the Reactome details page they could then click through to the diagram (as long as they know how!)

**Comment by tschaka1904** [comment]
Maybe, Reacomte could open in their application a little tooltip saying: 'Open Pathway in Reactome' or so.

**Comment by bmeldal** [comment]
Maybe. Need to decide which element(s) in the diagram would have that function as some already have tooltips.

**Comment by bmeldal** [comment]
Behaviour of Reactome Logo can't be changed but Sangya thought people didn't necessarily want to go to Reactome if we could offer the option to open the widget in a new tab.

**Comment by tschaka1904** [comment]
This issue has to carried out to reactome, as we can't recreate the link and we would double the functionality! If we keep trying to make users aware of it (Twitter, help, training), we could just stick with that.

**Comment by bmeldal** [comment]
Some of the issue may also be resolved once we come up with a better version of our table above the diagram #136

**Comment by bmeldal** [comment]
Added to Jira:
https://intact.atlassian.net/browse/CP-231
