### ISSUE TITLE
complexTAB readme - special characters down't display

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#149]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search existing issues for a similar problems/requests
[ ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**
Lots of "?" in diamonds not displaying special characters (at least double quotes don't show)

Unique identifier for complex, represented as �ac�, where ac is the unique primary identifier of the molecule in the Complex Portal database. Multiple identifiers can be separated by "|". 

**Expected behaviour**
Display special character correctly.

Unique identifier for complex, represented as "ac", where ac is the unique primary identifier of the molecule in the Complex Portal database. Multiple identifiers can be separated by "|". 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behaviour?**
difficult for user to understand what's being instructed!

**Please tell us about your environment:**
Windows Firefox broken, Windows Chrome ok.

**Comment by tschaka1904** [comment]
This seems to a FireFox issue as this also happens in FireFox on Mac

**Comment by bmeldal** [comment]
Fixed. Probably through Firefox updates.
