### ISSUE TITLE
Pull Orphranet names from OLS

### ISSUE THREAD

**Issue by tschaka1904** [Complex-Portal/complex-portal-view#15]
We want to pull the names of the Orpqranet XRefs in.

**Comment by tschaka1904** [comment]
Apparently we need to look for EFO an Orphranet XRefs.

**Comment by bmeldal** [comment]
Yes, all disease xrefs have DB type=EFO as EFO has xrefs to all the major Disease DBs and retained their ACs.

Orphanet, OMIM (should all be replaced in Complex portal), HP (human phenotype ontology) and EFO terms themselves.

**Comment by bmeldal** [comment]
Just looked at the link to the code: you need to add HP (see above)!
OMIM should have all been replaced but if you find any OMIM xrefs please let me know.
