### ISSUE TITLE
Header spacing too narrow - again!

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#150]
There's almost no white space above "GO - Cellular Component". I thought we added some but it's no longer there. 

Should be more like the spacing between "Expression and Cellular Location" and "Gene Expression Map" headers.

Some of the other headers have similarly little spacing but sometimes it looks less squished depending on the available data in the section above a given header.

**Comment by tschaka1904** [comment]
Changed form: 
![screen shot 2017-06-30 at 16 39 36](https://user-images.githubusercontent.com/5269116/27743121-df3b1766-5db2-11e7-8fe8-7cf545d53bd8.png)

To: 
![screen shot 2017-06-30 at 16 39 15](https://user-images.githubusercontent.com/5269116/27743126-e2af345e-5db2-11e7-9f03-21db04290691.png)

**Comment by bmeldal** [comment]
Much better. Will that spacing be standard for all header spacings?
