### ISSUE TITLE
Renaming for dropdown menu options

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#151]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search existing issues for a similar problems/requests
[x ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**
Default terms

**Expected behaviour**
Terms that actually mean something to the user:
MI features - binding regions
UniProt Features - be specific which features we are displaying, I think it's domains...?
Superfamilies - needs to be more specific but not 'domains'
Interactors - colour in unique interactors - Roser thought it was the binding regions but confused as there was no data for binding regions in her example.

**What is the motivation / use case for changing the behaviour?**
Users who don't now the PSI-MI CVs don't understand the selection options.

**Comment by tschaka1904** [comment]
Please come up with the suggestions of the new names and I'll update them.

**Comment by bmeldal** [comment]
Sorry, need to confer with @sandraorchard 

MI feature = binding region
UniProt features: what is actually in it? I know we only take a subset of what they can supply. Where is it documented?
Superfamilies: probably leave as is as it's =! domains (they are among the UP features)
Interactors = colour in Unique Participants

**Comment by tschaka1904** [comment]
Maybe @colin-combe can help here: 

> UniProt features: what is actually in it? I know we only take a subset of what they can supply. Where is it documented?

**Comment by tschaka1904** [comment]
> Interactors = colour in Unique Participants

I would go for 'Unique Participants' as 'colour in Unique Participants' is quite long.

**Comment by bmeldal** [comment]
>I would go for 'Unique Participants' as 'colour in Unique Participants' is quite long.

Yes, I had that first, then wasn't sure if users understood what was meant...

**Comment by sandraorchard** [comment]
I think ' Unique Participants' should work.
'UniProt features' is a difficult one, as its a curated collection of domains, repeats,  regions of compositional bias, regions, motifs, sequence similarities and coiled coils - and I don't know which Colin uses. 'UniProt curated features' may be a bit more  descriptive, or 'UniProt curated domains'

**Comment by bmeldal** [comment]
And then we can add some context-specific help with more details as to where the annotated features come from.

**Comment by colin-combe** [comment]
Hi - sorry for delay getting back to you on this,
its the domains we are taking from the UniProtKB  data (category = "DOMAIN"),
c

**Comment by bmeldal** [comment]
Yes, @colin-combe those are the features we are wondering how to name them. So you only brought in the UniProt 'domains'? How do they differ from the 'superfamilies' - and where do they come from again?

Shows how urgently we need documentation for this if I don't know what exactly we are showing ;-)

**Comment by sandraorchard** [comment]
The difference between SuperFamilies and DOMAIN I can explain to you.
