### ISSUE TITLE
Superfamily link broken - again

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#152]
In the Complex Viewer none of the examples we looked at during today's testing were displaying data for Superfamilies. Smells like a broken link / bug!

**Comment by tschaka1904** [comment]
I guess this request is done by the viewer @colin-combe? If so, would it be possible to have a callback or so to be notified if a request hasn't been successful?

**Comment by tschaka1904** [comment]
I'll close this issue, as this should be solved with #153
