### ISSUE TITLE
Display message when no data in viewer menu

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#153]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search existing issues for a similar problems/requests
[x ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**
bars stay white

**Expected behaviour**
either grey-out or display a message that there is no data available for this type of feature

**What is the motivation / use case for changing the behaviour?**
a) User thinks something has gone wrong when nothing is displayed
b) We have to guess if there is no data or external API has gone down again! #152

**Comment by tschaka1904** [comment]
Please provide examples.

**Comment by bmeldal** [comment]
Hemoglobin :)
http://www.ebi.ac.uk/complexportal/complex/EBI-9008420

**Comment by colin-combe** [comment]
The proteins are now filled grey with a tooltip saying 'no annotations' if retreiving the annotations came back empty. Not perfect solution but should help with this. (demo @ http://complexviewer.org)

**Comment by bmeldal** [comment]
Once @tschaka1904 has redeployed the new version this can be closed.
