### ISSUE TITLE
ECO:0000353 without xref to IntAct

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#154]
Not sure if it's a bug or wrong ECO assignment (I fixed one of those already). I didn't note which complex it was today that had this issue but could I have a list with all such complexes so I can do some spot checks, please?

Could also be in cases where expt evidence comes from PDB/EMDB. How do we deal with those cases?

@sandraorchard

**Comment by tschaka1904** [comment]
Let me know which codes are interesting for you.

**Comment by bmeldal** [comment]
Just ECO:0000353, ECO:0005542 & ECO:0005543

(Rest are codes for inferred complexes or parent codes as they are an ontology)

**Comment by tschaka1904** [comment]
Can you let me know what are the corresponding new codes are?

**Comment by tschaka1904** [comment]
## ECO:0000353:
EBI-9108670
EBI-6676762
EBI-9019469
EBI-9021558
EBI-9016042
EBI-9293677
EBI-9293944
EBI-9098433
EBI-9696362
EBI-10817173
EBI-10099500
EBI-10818080
EBI-10691160
EBI-10705742
EBI-11173119
EBI-13952815
EBI-13950591
EBI-13950930
EBI-13950990
EBI-1208707
EBI-2464572
EBI-9101635
EBI-8870047
EBI-6923225
EBI-11891635
EBI-9094683
EBI-11684256
EBI-10705394
EBI-10705755
EBI-9551654
EBI-10099039
EBI-11425837
EBI-11821404
EBI-11600820
EBI-11705377
EBI-13643197
EBI-13948707
EBI-12501968
EBI-9082861
EBI-9019460
EBI-6552438
EBI-9004110
EBI-8870238
EBI-11891101
EBI-9685966
EBI-11896191
EBI-10713281
EBI-10205244
EBI-11786062
EBI-12518227
EBI-13638205
EBI-13949147
EBI-13949593
EBI-11838611
EBI-8786881
EBI-2881436
EBI-9545427
EBI-9696921
EBI-11166946
EBI-10713638
EBI-10714791
EBI-11173357
EBI-783421
EBI-11560071
EBI-13949715
EBI-9098346
EBI-2353861
EBI-9003834
EBI-9207004
EBI-2337596
EBI-8789430
EBI-6913771
EBI-11890315
EBI-11892130
EBI-11890798
EBI-9105217
EBI-10955195
EBI-10717502
EBI-10098681
EBI-10691103
EBI-10691260
EBI-11786893
EBI-11315673
EBI-12510858
EBI-9085280
EBI-9116675
EBI-2464615
EBI-9212872
EBI-8869931
EBI-11890834
EBI-9105241
EBI-9080360
EBI-9105417
EBI-9010427
EBI-9673795
EBI-10828300
EBI-10711453
EBI-10099054
EBI-11302894
EBI-13948980
EBI-13949872
EBI-12510070
EBI-12560350
EBI-13636498
EBI-13949218
EBI-13645703
EBI-11840849
EBI-9009008
EBI-6923348
EBI-11893385
EBI-9102292
EBI-2431547
EBI-9993621
EBI-9994283
EBI-9545942
EBI-9687057
EBI-11582133
EBI-10098921
EBI-10705984
EBI-10825904
EBI-11174708
EBI-11297444
EBI-12501304
EBI-12513428
EBI-12501958
EBI-11893010
EBI-1253636
EBI-9007893
EBI-9009119
EBI-8793636
EBI-8784378
EBI-9004163
EBI-9009036
EBI-8786862
EBI-11880520
EBI-11891862
EBI-11891053
EBI-11892159
EBI-2528323
EBI-9985892
EBI-9545664
EBI-9674411
EBI-10098135
EBI-10043504
EBI-11295018
EBI-12654601
EBI-12502440
EBI-12502251
EBI-12557887
EBI-12560849
EBI-12735745

**Comment by tschaka1904** [comment]
## ECO:0005542
EBI-2352849
EBI-9018925
EBI-11740766
EBI-11785577
EBI-11896755
EBI-14000950
EBI-2315278
EBI-11740773
EBI-11896492
EBI-1253654
EBI-13949356
EBI-13941879
EBI-13639240
EBI-11785112
EBI-13949692

**Comment by tschaka1904** [comment]
## ECO:0005543
EBI-11824157
EBI-12517329
EBI-12557797
EBI-11892279
EBI-12506480
EBI-12510806
EBI-12560506
EBI-12509908
EBI-12516644
EBI-12516453
EBI-12509997
EBI-12510033
EBI-12516475
EBI-12557416
EBI-12514570

**Comment by bmeldal** [comment]
Ok, not a bug, these have evidence in PDB! (I checked only a few and same for all) @sandraorchard, how should we handle this? At the moment it says evidence by PI without a link. Might be fine until someone queries it...

**Comment by bmeldal** [comment]
Duplicated by Jira:
https://intact.atlassian.net/browse/CP-137
Added to Jira:
https://intact.atlassian.net/browse/CP-182
