### ISSUE TITLE
"Reset" button should also reset to binding region view

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#157]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search existing issues for a similar problems/requests
[x ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**
"Reset" only resets the proteins back to circles and brings them back into the viewer space

**Expected behaviour**
Also reset the dropdown menu to the default of "binding sites"

**What is the motivation / use case for changing the behaviour?**
User request through testing.

**Comment by tschaka1904** [comment]
How about renaming it to 'Collapse all'?

**Comment by bmeldal** [comment]
Ok, that makes it clear what it currently does.
