### ISSUE TITLE
back button intermittently fails

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#160]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search existing issues for a similar problems/requests
[ ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**
Search hangs when going from details page back to results page.

**Expected behaviour**
Should reload results page.

**Minimal reproduction of the problem with instructions**
hit <back> button or click on <browser back> arrow.

**What is the motivation / use case for changing the behaviour?**
Have to redo full search - it's annoying!

**Please tell us about your environment:**
Fails in Firefox for Windows
works in Chrome for Windows

**Comment by tschaka1904** [comment]
Okay I could reproduce it and saw the error. Seems to be something FF specific.

**Comment by tschaka1904** [comment]
Okay, after some research we're going to change the way we build the URLs.

Currently it is working like this:
`http://www.ebi.ac.uk/complexportal/complex/search?query=EBI-9008420&page=1&species=example1,example2`

The filter for species is displayed like this:
`species=example1,example2`

What we need/want to do is: 
`species=example1&species=example2`

Which would result in:
`http://www.ebi.ac.uk/complexportal/complex/search?query=EBI-9008420&page=1&species=example1&species=example2`

**Comment by tschaka1904** [comment]
This is solved now.
