### ISSUE TITLE
'Complex not found' not working

### ISSUE THREAD

**Issue by sandraorchard** [Complex-Portal/complex-portal-view#161]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search existing issues for a similar problems/requests
[ ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**
Complex not found not working properly - hanging for a long period of time, apparently still searching.

**Expected behaviour**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behaviour?**

**Please tell us about your environment:**

**Comment by tschaka1904** [comment]
Is this happening on a specific search? Or browser?

**Comment by sandraorchard** [comment]
Seems to be working fine today. It was in a recent version of Firefox, Sorry didn't take note of the query.

**Comment by tschaka1904** [comment]
Please reopen if it reappears.
