### ISSUE TITLE
homologous complexes open in IntAct, not Complex Portal

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#163]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search existing issues for a similar problems/requests
[ ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**
When the evidence for the complex is a homologous complex our evidence line in the header searches IntAct:
http://www.ebi.ac.uk/complexportal/complex/EBI-14348029
![image](https://user-images.githubusercontent.com/10517124/28419342-8d70b87e-6d56-11e7-8fb0-b487bef04651.png)
directs to http://www.ebi.ac.uk/intact/query/EBI-13943368
![image](https://user-images.githubusercontent.com/10517124/28419412-c4379652-6d56-11e7-9183-8e69c17fd53b.png)

**Expected behaviour**
but needs to search CP: http://www.ebi.ac.uk/complexportal/complex/search?query=EBI-13943368&page=1
![image](https://user-images.githubusercontent.com/10517124/28419494-fb092448-6d56-11e7-8c07-adf0b2fbe30e.png)

**What is the motivation / use case for changing the behaviour?**
Not strictly a bug as I told you what to do so my fault for not considering where it links to!
All IntAct xrefs that are inferred by homology, orthology or paralogy need to link to the CP search.

**Comment by bmeldal** [comment]
This needs to come from the DB: We need to create a new DB=complexportal with search url pointing to the CP, then we can change all inferred-from xrefs to the new DB.

@pporrasebi one for us to fix in the ontology when we are both back...

Then one of the developers can script the changes.

**Comment by bmeldal** [comment]
@pporrasebi added the new term to the obo file. 

Remaining to do:
- [ ] run CV update - to propagate to Editor
- [ ] run release - to propagate to WS, website etc...

**Comment by tschaka1904** [comment]
This complex has no XRef to any Complex Portal or IntAct entry: http://www.ebi.ac.uk/complexportal/complex/EBI-12555370

**Comment by bmeldal** [comment]
@sandraorchard all MORF* complexes are inferred by homology or a child thereof but none have an xref to an entry with expt evidence. Shall I change them all to 'modelled'?

**Comment by IntAct-EBI** [comment]
OK, if that's the case.

**Comment by bmeldal** [comment]
All MORF* complexes fixed. Problem was that there was GO evidence but not interaction evidence so Mila got some of the codes muddled. I checked them all and fixed what was wrong.

**Comment by bmeldal** [comment]
Bug has changed, now the link has fully disappeared. Moved to:
https://intact.atlassian.net/browse/CP-225
