### ISSUE TITLE
Latest complexviewer is not showing completely

### ISSUE THREAD

**Issue by tschaka1904** [Complex-Portal/complex-portal-view#164]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search existing issues for a similar problems/requests
[ ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**

I've updated to the latest version of the viewer and I experience some issues. Here a gif:
![jul-31-2017 16-15-20](https://user-images.githubusercontent.com/5269116/28784610-cfd26236-760b-11e7-821e-d9cba36cf8bb.gif)

1. The loading spinner is loading in the middle of the page.
2. The viewport for the viewer seems not to use its 100%.

@colin-combe did you ever experience something like this?

###### Just a few guidelines for how to write effective and good GitHub issues: [HOW WE WRITE GITHUB ISSUES](https://wiredcraft.com/blog/how-we-write-our-github-issues/)

**Comment by colin-combe** [comment]
Ah, yes, thanks Max.

When I was making the demo page, it seemed wrong having the styling of the SVG element hardcoded into the component (I used flex layout for the demo page). 

Its initialisation routine used to contain:
`    
this.svgElement.setAttribute('id', 'networkSVG');
this.svgElement.setAttribute("width", "100%");
this.svgElement.setAttribute("height", "100%");
this.svgElement.setAttribute("style", "display:block;");
`

but this is now replaced by: 
`this.svgElement.setAttribute('id', 'complexViewerSVG');`

(I gave it a more specific id)

Adding the following to your css should make the behaviour the same as before:
`#complexViewerSVG {
height: 100%;
width: 100%;
display: block;
}`

unless we find using css styles behaves differently from height and width attributes directly on the element.

Let me know if adding the css fixes...
cheers,
c

**Comment by colin-combe** [comment]
p.s. the change to ID is in the most recent version in MICommunity/master

**Comment by tschaka1904** [comment]
Thanks Colin! It works, almost! The spinner seems to centre it self in the middle of the page, rather in the middle of viewer :(

**Comment by colin-combe** [comment]
I'll have a look at the spinner next week,
Cheers,
C


Quoting Maximilian Koch <notifications@github.com> on Wed, 02 Aug 2017  
12:56:57 +0000 (UTC):

> Thanks Colin! It works, almost! The spinner seems to centre it self  
> in the middle of the page, rather in the middle of view :(
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Complex-Portal/complex-portal-view/issues/164#issuecomment-319663895



-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by colin-combe** [comment]
Position needs to set to relative on the target div to get the spinner to centre within it.

Please let me know if this solves prob,
cheers,
c

**Comment by tschaka1904** [comment]
All solved! :)

**Comment by tschaka1904** [comment]
![seasick](https://user-images.githubusercontent.com/5269116/29269906-f1ba34b0-80eb-11e7-9a76-197d8bd0fb3c.gif)
