### ISSUE TITLE
no result search hangs

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#166]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search existing issues for a similar problems/requests
[ ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**
"No results" search hangs: 

Search for aca - brings up normal 'no results' message.
now change term in top search bar to h/aca --> search results update to "no results for h/aca" but moving bar continues to move.

search for h/aca from home page --> turning circle doesn't stop, no "no results" message displayed

Same results if search for "h/aca" (with double quotes)

**Please tell us about your environment:**
Firefox and Chrome for mac

**Comment by bmeldal** [comment]
and this is the complex I was looking for:
http://www.ebi.ac.uk/complexportal/complex/EBI-11175861
H/ACA is in the function statement, I thought that was indexed?
(H/ACA is not a synonym as it's the pre-assembly complex and we don't curate it as it's not functional)

**Comment by tschaka1904** [comment]
Okay, I had a look into that it seems that the Solr can't deal with a search containing `/`. This might be something @noedelta or @git4anjali know a little better? Is that something we can configure?

**Comment by bmeldal** [comment]
Any search with "/" in it hangs now.

Moved to Jira:
https://intact.atlassian.net/browse/CP-208
