### ISSUE TITLE
List search runs out of memory

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#168]
On behalf of Astrid Lægreid <astrid.lagreid@ntnu.no>:

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search existing issues for a similar problems/requests
[ ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**
Submit attached file of nearly 4000 UniProt IDs:
[Human_GO0003700_UniProtAcc_HGNC-symbols-1.xlsx](https://github.com/Complex-Portal/complex-portal-view/files/1291896/Human_GO0003700_UniProtAcc_HGNC-symbols-1.xlsx)

search runs out

**Expected behaviour**
retrieve list of complexes that contain at least one member of input list

**Minimal reproduction of the problem with instructions**
run search from homepage

**What is the motivation / use case for changing the behaviour?**
trying to retrieve all complexes annotated to proteins with transcription factor binding annotations

**Please tell us about your environment:**
Astrid: Windows
Birgit: Mac

**Comment by tschaka1904** [comment]
This file as multiple problems. First of all it has IDs with a `/` in it, which seems to be an issue for some reason the the encoding (Relates to issue #166). 

Furthermore, the error is an http `413`, which basically says that the request is to long. We're doing a `get request`. One option could be to higher up the size of the possible `RequestHeader and Buffer` or we would need to implement a `post request` method into the web service.

**Comment by bmeldal** [comment]
Now it gives 4 results.

**Comment by bmeldal** [comment]
related:
https://intact.atlassian.net/browse/CP-208
