### ISSUE TITLE
New icon for Arabidopsis (Brassica) and Danio (Zebrafish)

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#170]
Max, we need to add two icons for 2 new complex species, both are already on the EBI font list:

Arabidopsis thaliana = Brassica icon
Danio rerio = Zebrafish icon

**Comment by tschaka1904** [comment]
Ok. There is a new form from the style lab here: https://docs.google.com/forms/d/e/1FAIpQLSe7_lFbhVdt-AJeGQChjkiab642nDkfKTVoNQRosPAKuBP3_g/viewform?c=0&w=1

**Comment by bmeldal** [comment]
The icon are there, ready to be used, we don't have to ask for new ones.

**Comment by bmeldal** [comment]
I've saved the link for future use.

**Comment by tschaka1904** [comment]
Ah, sorry I see! 👍 _Arabidopsis thaliana_ is a plant right? Should we start introducing colour codes like the Atlas guys? 

![screen shot 2017-09-15 at 10 01 43](https://user-images.githubusercontent.com/5269116/30474859-e7185cf6-99fc-11e7-81f1-1296a7c73fa4.png)

**Comment by bmeldal** [comment]
Yes, Arabidopsis thaliana is a plant, what Zengyan is starting. Part of the Brassica family that includes broccoli and cauliflower and a lot of other stuff that doesn't look similar just because it's been selected by farmers over centuries but genetically still closely related.

Colours: could do but wouldn't lump fungi, insects, annelids (worms) and birds in one colour! Blue in GXA.

**Comment by tschaka1904** [comment]
Your call! Maybe something to discuss with Sangya and Xav.

**Comment by bmeldal** [comment]
Yes, we can talk about it next Thursday.
