### ISSUE TITLE
Think about integrating OLS WS to retrieve interactor types

### ISSUE THREAD

**Issue by tschaka1904** [Complex-Portal/complex-portal-view#172]
As part of assigning the legend logos to the participant table, we currently hardcode the terms. At the time of development, it was never mentioned that there could be more than 4: 

- small molecule
- protein
- single stranded deoxyribonucleic acid
- ribonucleic acid

Apparently, it is the case that we have to ribonucleic acid more than one type. I think this was okay and sufficient at the time, but #122 points out that have more terms. Maybe we want to talk to OLS directly and implemented an OLS service.

**Comment by bmeldal** [comment]
Moved to Jira:
https://intact.atlassian.net/browse/CP-222
