### ISSUE TITLE
Sort participants in WS for participant table

### ISSUE THREAD

**Issue by tschaka1904** [Complex-Portal/complex-portal-view#174]
We sort the participants based on `interactorType`, but this should probably be already sorted or in a different structure when it comes from the WS.

**Comment by bmeldal** [comment]
I'd sort by interactor type first, then alphanumerically by name (humans are better at reading names than IDs!).

**Comment by bmeldal** [comment]
Moved to Jira:
https://intact.atlassian.net/browse/CP-221
