### ISSUE TITLE
Mapping proteins to the organism annotated for the complex

### ISSUE THREAD

**Issue by ghost** [Complex-Portal/complex-portal-view#176]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search existing issues for a similar problems/requests
[ ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**
The two complexes EBI-10916423 and EBI-9008846 have the same composition in terms of Uniprot ACs but one is annotated for Homo sapiens and the other for Mus musculus. I don't know if there are (but I guess there might as well be) other cases like this.

**Expected behaviour**
The components of each complex are annotated with Uniprot ACs from the source organism. In this case protein CHRNA4 has Uniprot AC P43681 for Human and O70174 for Mouse.

**What is the motivation / use case for changing the behaviour?**
Simply that Uniprot ACs of the components correspond to the organism to which the complex belong.

**Comment by bmeldal** [comment]
Thank you, @robmosca It was human error, thanks for spotting and reporting it.
All fixed in the database. It will be updated on the website and in the ftp files with the next release.

**Comment by bmeldal** [comment]
@tschaka1904 please close ticket, I don't have the button.
