### ISSUE TITLE
request to add complex ID to entry page

### ISSUE THREAD

**Issue by NancyCampbell** [Complex-Portal/complex-portal-view#181]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search existing issues for a similar problems/requests
[x] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**

Feature request rather than a bug. The complex ID does not seem to be present on the main entry page
**Expected behaviour**

Add complex ID on the main entry page
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behaviour?**

**Please tell us about your environment:**

Max OSX, tried both firefox quantum 57.0.1, chrome 63.0.3239.84 (Official Build) (64-bit) --> complex ID does not seem to be presesnt on the entry page of the complex whichever I use

**Comment by bmeldal** [comment]
Hi Nancy,

We’ve left it out deliberately and they will be added once we have the new CPX-xxx identifiers. Noe is working on them. They will also included versioning.

Don’t worry, old AC remain as secondaries and we are working with Tony who will update the GO files.

**Comment by NancyCampbell** [comment]
thank you :-)
