### ISSUE TITLE
EMDB Cross reference links are broken

### ISSUE THREAD

**Issue by edwong57** [Complex-Portal/complex-portal-view#182]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search existing issues for a similar problems/requests
[ ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**

Links to EMDB on this page: https://www.ebi.ac.uk/complexportal/complex/EBI-9010849
are broken. There's an extra bit in the URL for 2594: https://www.ebi.ac.uk/complexportal/www.ebi.ac.uk/pdbe/entry/emdb/2594 and the link goes to a blank complex portal page

**Expected behaviour**

Should go to: https://www.ebi.ac.uk/pdbe/entry/emdb/2594

**Minimal reproduction of the problem with instructions**

Click on any EMDB link on this page: https://www.ebi.ac.uk/complexportal/complex/EBI-9010849

**What is the motivation / use case for changing the behaviour?**

Broken links.

**Please tell us about your environment:**

Firefox, version 57.0.4

**Comment by bmeldal** [comment]
Thanks, Edith. I'll get @pporrasebi to look at it.

We've already fixed this link in August and the bug's come back: https://github.com/Complex-Portal/complex-portal-view/issues/38

**Comment by bmeldal** [comment]
Still broken. 
@pporrasebi @noedelta

**Comment by bmeldal** [comment]
Duplicated in Jira:
https://intact.atlassian.net/browse/CP-113
