### ISSUE TITLE
Unknown identifier for EBI-16411854

### ISSUE THREAD

**Issue by llambourne** [Complex-Portal/complex-portal-view#183]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search existing issues for a similar problems/requests
[ ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

Hi,

I downloaded your homo sapiens data in the complextab format. On the third row, under the `Identifiers (and stoichiometry) of molecules in complex` column, there is an identifier `MULT_27_human`. It's not clear what that corresponds to. When I go to the page of the corresponding complex: EBI-16411854 the complex diagram does not display (it does display for other complexes) and the participant that seems to correspond to that identifier links to a broken link on MatrixDB. 

**Minimal reproduction of the problem with instructions**

Go to
https://www.ebi.ac.uk/complexportal/complex/EBI-16411854
click on Laminin-211 link

**Please tell us about your environment:**

Mac OSX, Chrome

Thanks for your time,
Luke

**Comment by bmeldal** [comment]
Hi Luke,

Thank you for contacting us. 

In this complex Laminin-211 is a subcomplex of Laminin211-nidogen complex. It should link to the EBI-xxx AC of Laminin-211 (EBI-2529716). The reason that the link to MatrixDB shows up is an internal Database error we are working on (as well as the broken link to MatrixDB).

We'll update you once we have fixed this bug.

Birgit

**Comment by bmeldal** [comment]
Note to team: Jira CP-126

**Comment by llambourne** [comment]
Hi Birgit,

Thanks for explaining that. OK, sounds good. 

Thank you! 
Luke

**Comment by bmeldal** [comment]
Links seem to be fixed and stable.
