### ISSUE TITLE
CDC13 erroneously included in systematic name of septin complex

### ISSUE THREAD

**Issue by michael-mcmurray** [Complex-Portal/complex-portal-view#184]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search existing issues for a similar problems/requests
[ ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**

In Systematic Name of Septin complex (CPX-1675) is the following: "
2xCDC3:2xCDC10:2xCDC11:2xCDC12:2xCDC13:SHS1"
**Expected behaviour**

CDC13 is not part of the complex. Not sure exactly what the correct name would be.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behaviour?**

Prevent erroneous association of Cdc13 with septin complex.
**Please tell us about your environment:**

Mac OSX

**Comment by bmeldal** [comment]
Hi Michel,
Thank you for reporting our mistake, it was human error. I have fixed it (by removing CDC13 in the systematic name) and it will be updated with the next release.
regards,
Birgit
