### ISSUE TITLE
CPX-1645 (Ste4-Ste8 heterodimer) incorrectly named in the Complex Portal

### ISSUE THREAD

**Issue by robnash** [Complex-Portal/complex-portal-view#185]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search existing issues for a similar problems/requests
[ ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**
This heterodimeric complex of a G-beta and G-gamma subunit involves Ste4p and Ste18p, and does not involve Ste8p, which encodes a silencing protein in yeast. So the name of the complex described on this page https://www.ebi.ac.uk/complexportal/complex/CPX-1645 should be the "Ste4-Ste18 heterodimer"
**Expected behaviour**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behaviour?**
Correct information :)

**Please tell us about your environment:**

**Comment by bmeldal** [comment]
Thanks, Rob. I hazard a guess it was a typo. Fixed at our end but will only be updated with the next IntAct/CP release at the end of June as we've just finished one yesterday..

**Comment by robnash** [comment]
No worries about timing etc. Just pointing this out, even though its minor.

Cheers,
Rob
