### ISSUE TITLE
UniProt links broken

### ISSUE THREAD

**Issue by LornaMGnify** [Complex-Portal/complex-portal-view#186]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search existing issues for a similar problems/requests
[ ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**
Current UniProt url is wrong so links don't work.

**Expected behaviour**
Links would work.

**Minimal reproduction of the problem with instructions**

https://www.ebi.ac.uk/complexportal/complex/CPX-1951

**What is the motivation / use case for changing the behaviour?**

**Please tell us about your environment:**

**Comment by bmeldal** [comment]
Hi Lorna.

It works for me right now. Please try again in case it was a temporary glitch.

Birgit

**Comment by LornaMGnify** [comment]
Hi Birgit - I was just about to update the thread. Following a bit more investigation I see that it is a chrome specifc thing. It seems to take the correct url in the link and then append another copy of the last part of the address - making it wrong. Not sure if it becuase of a UniProt redirect or someting, but I notice it on our site too. Very weird.

**Comment by bmeldal** [comment]
I just tested it on Firefox, Chrome and Safari and last night on my phone. It works on all those platforms. 

Please let me know if the problem persists for you.
