### ISSUE TITLE
typo mitochondiral in CPX-1379

### ISSUE THREAD

**Issue by gasteig** [Complex-Portal/complex-portal-view#187]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search existing issues for a similar problems/requests
[ ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**

There is a typo "mitochondiral" in CPX-1379

**Expected behaviour**

"mitochondrial"

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behaviour?**

**Please tell us about your environment:**

**Comment by bmeldal** [comment]
Fixed. Thanks for reporting.
