### ISSUE TITLE
Link to XML 3.0 is wrong

### ISSUE THREAD

**Issue by julie-sullivan** [Complex-Portal/complex-portal-view#19]
https://complex-portal.github.io/complex-portal-view/download

Is the 3.0 link correct?

ftp://ftp.ebi.ac.uk/pub/databases/intact/complex/current/psi25/

Should that go to here instead?

ftp://ftp.ebi.ac.uk/pub/databases/intact/complex/current/psi30/

**Comment by bmeldal** [comment]
Julie is right, it's pointing to the wrong folder (copy-paste issue?).
