### ISSUE TITLE
Data truncated on some pages

### ISSUE THREAD

**Issue by LornaMGnify** [Complex-Portal/complex-portal-view#190]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search existing issues for a similar problems/requests
[ ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**

only first part of the first sentence of the function section is showing.

**Expected behaviour**

expect to see all of the information

**Minimal reproduction of the problem with instructions**

see CPX-1556

**What is the motivation / use case for changing the behaviour?**

**Please tell us about your environment:**

Mac OS High Sierra, Firefox 63.0.1

**Comment by bmeldal** [comment]
Hi Lorna.
I checked our DB and that's all the description the curator has given but the full stop is missing. I have added the full stop but it won't show til the next release.
Birgit

**Comment by LornaMGnify** [comment]
In the downloaded version of this entry, there are many more lines of information provided.
(also there is a typo in this first sentence "unwinings" should presumably be "unwinding")

**Comment by bmeldal** [comment]
Hi Lorna,

We looked into the logs and can't find a longer description statement. Could you please send us the file you downloaded so we can track down the mistake? Either attach it here or email complexportal AT ebi.ac.uk.

I've fixed the typo, thank you for spotting that :)

Birgit

**Comment by LornaMGnify** [comment]
I'm afraid I can't find the original downloaded .xml file that this came from, but here is the content parsed and formatted as CC lines. 

[CPX-1556.txt](https://github.com/Complex-Portal/complex-portal-view/files/2644682/CPX-1556.txt)

**Comment by bmeldal** [comment]
Thank you. I will check with the original curator what happened here and if it was deleted on purpose.

**Comment by LornaMGnify** [comment]
looking at the xml download from the site, I can see the various sentences, but separated out under different evidence tags? Perhaps this is a concatenation of the various complexes that contribute to this super-complex?

**Comment by sandraorchard** [comment]
It has definitely been truncated, and by error. I'll use the CPX-1556.txt file to fix, but it won't be correct until the next release.

**Comment by LornaMGnify** [comment]
I may have spotted some others like this, but can't remember for sure. If I spot any more I will continue to report them.

**Comment by bmeldal** [comment]
Thank you for your help, Lorna.
If you find any other errors, just open a new ticket. I'll close this one for now.
Birgit
