### ISSUE TITLE
ECM8 versus EMC8

### ISSUE THREAD

**Issue by lbreuza** [Complex-Portal/complex-portal-view#199]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search existing issues for a similar problems/requests
[ ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**

I guess the acronym is EMC and not ECM since it stands for ER Membrane Complex. 

see in UniProtKB: 
DR ComplexPortal=CPX-5882; Endoplasmic reticulum membrane complex, ECM8 variant
DR ComplexPortal=CPX-5883; Endoplasmic reticulum membrane complex, ECM9 variant

**Expected behaviour**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behaviour?**

**Please tell us about your environment:**

**Comment by bmeldal** [comment]
Thanks for spotting and reporting this typo. All fixed, also alias fields and respective human entries.

Changes will appear on the public site in the next release.
