### ISSUE TITLE
Link to originating data sources

### ISSUE THREAD

**Issue by yochannah** [Complex-Portal/complex-portal-view#20]
The portal looks great! A tiny observation - I clicked on the uniprot logo in this screenshot, thinking it might take me to uniprot. The same probably holds true for the other logos as well?

![image](https://cloud.githubusercontent.com/assets/9271438/23264678/1aa5a51a-f9da-11e6-8bef-77f7ba8ee551.png)

**Comment by bmeldal** [comment]
Yes, I think we have to hyperlink the logos to the individual resources. I have to check with Ruth for the UCL team and Sameer for CEITEC, the others should be obvious.

**Comment by tschaka1904** [comment]
@bmeldal wasn't there also a discussion about a elixir logo?

**Comment by bmeldal** [comment]
Yes, but don't know yet which resources will be core Elixir resources. It will be more likely IntAct in the first round rather than CP.
