### ISSUE TITLE
Non-functioning links in the Pathways section

### ISSUE THREAD

**Issue by andrewsu** [Complex-Portal/complex-portal-view#203]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search existing issues for a similar problems/requests
[ ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**
The links to Reactome in the "Pathways" section do not work for me.  For example, on https://www.ebi.ac.uk/complexportal/complex/CPX-2158, none of the underlined links in the screenshot below work.

![image](https://user-images.githubusercontent.com/2635409/233701263-46392ab7-c8a6-4ddf-b5b8-5960110e3e63.png)

**Expected behaviour**
The underlined text in the screenshot above would be hyperlinks to the corresponding Reactome page.

**Minimal reproduction of the problem with instructions**
On https://www.ebi.ac.uk/complexportal/complex/CPX-2158 and https://www.ebi.ac.uk/complexportal/complex/CPX-152

**What is the motivation / use case for changing the behaviour?**
Display useful links to more information

**Please tell us about your environment:**
Tested on Windows 11 using both Edge and Firefox

**Comment by hHermjakob** [comment]
Hi Andrew,
the "Pathways" table you commented on is actually not meant for navigation links to external Reactome, but as a navigation tool to the imported Reactome visualisation widget directly below the table. So nothing is broken on the technical side, but we'll take it as a note on usability.

**Comment by tschaka1904** [comment]
I can confirm @hHermjakob statement about the functionally of these links. They are intended to navigate the visualization just underneath. I was the dev putting this together and also had brief look at the source code, as it has been a few years working with it. One way might be to add a fourth column, something like "Go to Reactome"

**Comment by andrewsu** [comment]
Ahh, I see it now.  I think my browser window was not scrolled down enough to notice the change in the Reactome widget underneath.  Thank you for the explanation -- I'll close the issue now...  Thanks for the the great resource!
