### ISSUE TITLE
PMID xrefs

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#21]
EBI-9008420
has one PMID xref in prod but table is empty in the new GH version

**Comment by bmeldal** [comment]
Should also be at the bottom of the page until we can split and assign them to the relevant sections.

**Comment by tschaka1904** [comment]
> EBI-9008420
has one PMID xref in prod but table is empty in the new GH version

This has been solved and was due a problem with the URLs. 

> Should also be at the bottom of the page until we can split and assign them to the relevant sections.

Just at the bottom?

**Comment by bmeldal** [comment]
Yup, I would just but <additional reading> to the bottom.

**Comment by tschaka1904** [comment]
This is going to go into a new issue.
