### ISSUE TITLE
if no GO function process looks 'lost'

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#22]
eg EBI-767678
has no GO molecular function so the process term in the right hand column looks like it's been shifted to the right accidentally as the left space is empty.

This is not an unusual case, we have lots of complexes without MF annotations.

**Comment by tschaka1904** [comment]
@sandraorchard & @bmeldal 

The problem is that I have allocated the space on the right side to it. How does UniProt do it?

**Comment by bmeldal** [comment]
UP don't use column, it's all one section below another. They are experimenting with an alternative view though which I tested for Sangya a few weeks ago. However, I'm not sure it would solve the problem :(

**Comment by bmeldal** [comment]
Closing it as can't think of a better option.
