### ISSUE TITLE
Reactome section missing

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#23]
just doesn't show right now.

**Comment by bmeldal** [comment]
Ok, it's back, but there is another issue that needs fixing with them:
https://complex-portal.github.io/complex-portal-view/complex/EBI-1245484
The complex is only one element of the diagram but the whole assembly process is highlighted making the diagram too small and unreadable. Even on the Reactome site it highlights too many elements.

**Comment by tschaka1904** [comment]
First issue is solved. The second issue needs to go into a new issue. I'm going to create one.
