### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#25]
When going to <next page> using the bottom pagination tool, please load the page to be on top by default.

**Comment by bmeldal** [comment]
This also happens when I hit "home" from within a details page, it opens the home page some bit down and I can't see the search box (until I scroll up).

**Comment by tschaka1904** [comment]
This needs some work later on the details page. We may want to allow to open and jump directly to a section. But this is work for the future.
