### ISSUE TITLE
EFO xrefs

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#27]
now these are sitting 'lost' in the right hand column...

**Comment by tschaka1904** [comment]
@sandraorchard & @bmeldal 
Do you have any ideas to solve this?

**Comment by bmeldal** [comment]
You had EFO and Chembl the other way round on Sandra's door. 
Or below each other.

**Comment by tschaka1904** [comment]
The problem is that for the Chembl XRefs it would look strange to go for the whole column. It has only a ID and no description.

**Comment by bmeldal** [comment]
We can grab the name/title from the Chembl entry.It should be the complex name - or their variant of it. Is there an API we could use?

**Comment by tschaka1904** [comment]
How does the Orphanet entry relate to Chembl?

**Comment by bmeldal** [comment]
Unrelated. Orphanet/EFO/HP etc ACs link to diseases, complexes identified as Chembl targets are drug targets as curated by Chembl.

**Comment by tschaka1904** [comment]
Ah! We're mixing here two XRefs! Got confused with Ticket name and talking about Chembl XRefs.

**Comment by bmeldal** [comment]
Add structure to disease text:

- Disease name in Bold
- AC as hyperlink - it would then make table irrelevant

Issue: needs tweaking in Editor as we use a free-text field to annotate diseases.

Should this be a different ticket???

**Comment by bmeldal** [comment]
Closing as related to making hyperlinks in text fields:
https://intact.atlassian.net/browse/CP-22
