### ISSUE TITLE
add PMID xrefs and ECO to GO

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#28]
We have the info for the evidence of the GO annotations in the editor and should display it. It probably isn't indexed yet so needs a bit more work. It would be great if we could show it similarly to Uniprot.
Go ID - Term name - PMID or Complex ID (if inferred from) - Evidence Code

And example of a complex with full GO annotations is EBI-1245484.

**Comment by tschaka1904** [comment]
Please give me a working example! 👍

**Comment by bmeldal** [comment]
Sorry... EBI-11740215

**Comment by bmeldal** [comment]
Added to Jira:
https://intact.atlassian.net/browse/CP-35
