### ISSUE TITLE
Place PMID to bottom of page

### ISSUE THREAD

**Issue by tschaka1904** [Complex-Portal/complex-portal-view#29]
Based on issue #21 

> Should also be at the bottom of the page until we can split and assign them to the relevant sections.

**Comment by sandraorchard** [comment]
..and synonyms?

**Comment by sandraorchard** [comment]
..and systematic name

**Comment by tschaka1904** [comment]
Yes. How do we want to name this section? 'Others'?

**Comment by bmeldal** [comment]
Going by UniProt style it would be "Names and References".

**Comment by sandraorchard** [comment]
Names and Publications sounds a bit better, avoids confusion with cross-references.

**Comment by bmeldal** [comment]
Yes, good point. Use Publications.
