### ISSUE TITLE
Evidence Section

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#33]
Suggestion:
Right below the Title section.
one line for ECO term name
one line for xref to Intact Evidence

NB: DIP xrefs will have to be manually updated after import (at the moment they are not hyperlinked as one cannot search DIP with an interaction evidence AC!). Some are IMEx xrefs to DIP, can also get IntAct codes when import done.

**Comment by bmeldal** [comment]
xrefs to DB=MatrixDB should go below the IntAct/Imex/DIP line
It's an equivalent entry.

**Comment by bmeldal** [comment]
Place either in green header or just below - need to play with options.

Line 1:
Hyperlinked text for ECO code that takes it through to ECO in OLS.
Abbreviate full names:
ECO:0000353 - inferred from physical interaction evidence
ECO:0005610 - inferred by homology
ECO:0005544 - inferred by orthology
ECO:0005546 - inferred by paralogy
ECO:0005547 - inferred by curator
ECO:0005543 - inferred from interaction evidence in mixed species
ECO:0005542 - inferred from multiple interaction evidence in same species
Don't display the code, I just added it for ref here!

The last 2 codes are a bit long(er). Any ideas @sandraorchard ?

Line 2:
Interaction Evidence: < Intact/IMEx AC >
For those complexes inferred by homology/orthology/paralogy the AC will be to another complex so we'll have to jig these round to the new Complex IDs!

For DIP ACs we'll have IntAct ACs soon. The IMEx ACs could then also be changed to Intact ACs.

**Comment by bmeldal** [comment]
Alternative:
Just one line with following structure:
< abbreviated ECO text > from < evidence AC >

Only caveat: ECO:0005542 will have 2 xrefs with qualifier "experimental evidence" so we'd have
"< abbreviated ECO text > from < evidence AC > and < evidence AC >"

**Comment by sandraorchard** [comment]
inferred from interaction evidence in mixed species - inferred from mixed species evidence
inferred from multiple interaction evidence in same species - inferred from single species evidence
If they don't understand click, they are one click away from an explanation
I think your second option is a bit too abreviated, but the IntAct evidence/inferred from could be placed adjacent to the line 
e.g. Inferred from physical interaction evidence EBI-xxxxxxx

**Comment by bmeldal** [comment]
"inferred from mixed species evidence": go for it!
"single species": how does that text distinguish from IPI code? To the uninitiated it will read the same but using different words.

You example line is effectively the same as my option 2 (I think).

**Comment by sandraorchard** [comment]
Just say Physical interaction evidence when we have evidence - we don't need inferred from in that case.
Option 2 - OK, sorry, I mis-understood it You can just pick one for mixed species, no need to show both.

**Comment by bmeldal** [comment]
Ok, so we'll have 
ECO:0000353 - physical interaction evidence
ECO:0005542 - inferred from single species evidence

Mixed spp evidence only has one xref to IntAct, single spp evidence has 2 as it's the 'sticky-tape' case.

**Comment by tschaka1904** [comment]
ECO:0000306 needs a description

**Comment by tschaka1904** [comment]
![screen shot 2017-03-27 at 14 16 37](https://cloud.githubusercontent.com/assets/5269116/24358190/39de28f8-12f8-11e7-844b-034945a0fc5c.png)

We could do this. But maybe we want to display underneath the viewer?

**Comment by bmeldal** [comment]
I find the headers too big. Maybe below viewer works better.
We don't need numbers in parenthesis as there is only 1 ECO xref and no more than 2 Intact xrefs.

We don't use ECO:0000306 anymore. We really must do the remapping of the old entries to the new ECO codes now! I have a mapping table somewhere, we should look at that next week.

**Comment by tschaka1904** [comment]
![screen shot 2017-03-27 at 14 53 32](https://cloud.githubusercontent.com/assets/5269116/24359763/372ec07c-12fd-11e7-9714-c19be60178ad.png)


Example having the evidences in between the viewer and the function.

**Comment by bmeldal** [comment]
We discussed above to change it to a simple sentence. That would shorten it as we won't need the headers.Forgot about it when I looked at it earlier.

In you example above it would be:
"Evidence **by physical association** in IntAct **Intact_AC**
with the bold part coming form the xref fields.

**Comment by bmeldal** [comment]
Oh, and then it can be above the viewer.

**Comment by tschaka1904** [comment]
Ah! okay! And where do you want the "Evidence and Conclusion Ontology"?

**Comment by bmeldal** [comment]
That's part of it. We'll display the plain text but link to the ECO page in the OLS. Might have to think about how to acknowledge ECO (which we could do by adding their icon to the contributors)

**Comment by bmeldal** [comment]
Current implementation is a little bulky. Let's look at constructing just one sentence with the method statement and the AC to the evidence.

**Comment by bmeldal** [comment]
Also, please add the ECO logo to the contributors. I'm attaching the high res symbol
<img width="1266" alt="eco logo 2" src="https://cloud.githubusercontent.com/assets/10517124/24420037/4e62a2f8-13e9-11e7-865f-a5e867d312ee.png">
<img width="777" alt="eco logo only" src="https://cloud.githubusercontent.com/assets/10517124/24420038/4e62d084-13e9-11e7-911e-edac6ae41482.png">

**Comment by bmeldal** [comment]
I would go for the "ECO"-only option, picture 2.

**Comment by tschaka1904** [comment]
> Also, please add the ECO logo to the contributors. I'm attaching the high res symbol
> <img width="1266" alt="eco logo 2" src="https://cloud.githubusercontent.com/assets/10517124/24420037/4e62a2f8-13e9-11e7-865f-a5e867d312ee.png">
> <img width="777" alt="eco logo only" src="https://cloud.githubusercontent.com/assets/10517124/24420038/4e62d084-13e9-11e7-911e-edac6ae41482.png">
> 

This needs to go a separate ticket. Please have a look to #70

**Comment by tschaka1904** [comment]
Okay. I get the idea with the sentence. This work nice in a 1:1 mapping. But what do we do if the have: 

- no IntAct evidence? (https://complex-portal.github.io/complex-portal-view/complex/EBI-8786862)
- multiple IntAct evidences? (https://complex-portal.github.io/complex-portal-view/complex/EBI-1209054)

**Comment by tschaka1904** [comment]
![screen shot 2017-03-30 at 14 58 48](https://cloud.githubusercontent.com/assets/5269116/24507810/6bf47adc-1559-11e7-8d1c-68996cfb2269.png)

Not the finial place, but it goes in the direction of your idea with the sentence.

**Comment by tschaka1904** [comment]
![screen shot 2017-03-30 at 15 03 09](https://cloud.githubusercontent.com/assets/5269116/24507992/079affd8-155a-11e7-8b07-6f2220a78031.png)

**Comment by tschaka1904** [comment]
ECO:0000266 is missing too.

**Comment by tschaka1904** [comment]
For the cases where I don't have the bit of the sentence (like ECO:0000266), I've done it like this: 
![screen shot 2017-03-30 at 15 13 00](https://cloud.githubusercontent.com/assets/5269116/24508489/7a5311e0-155b-11e7-9906-b2a46aaf3d18.png)


This is based on complex: EBI-1209357

**Comment by bmeldal** [comment]
I prefer it in the header - it's matches Uniprot more.

Those without a description are the ones we need to re-map. I'll sort it out with you next week when I have dug out the mapping table (there is a Jira ticket for this already :) ).

If there is no exp-evid or inferred-from we just have the wording from the ECO term. This should only be for ECO:0005547 (and the old ECO:0000306).

**Comment by tschaka1904** [comment]
> If there is no exp-evid or inferred-from we just have the wording from the ECO term. This should only be for ECO:0005547 (and the old ECO:0000306).

They currently say: Evidence by [ECO:0005547](url)

**Comment by bmeldal** [comment]
Can we replace the ECO code with the actual text description for all codes? If it's to complex by ticket we'll have a look together next week.

**Comment by tschaka1904** [comment]
We always display the text description, unless I don't have one.

**Comment by bmeldal** [comment]
There is a shortlabel and fullname in the editor. And OLS definitely supply a description.

**Comment by tschaka1904** [comment]
In theory we should always have a description, right?

**Comment by tschaka1904** [comment]
I wouldn't recommend that. [ECO:0005547 in OLS](http://www.ebi.ac.uk/ols/ontologies/eco/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FECO_0005547) as an example. The names are massive and that will look very crowded.

**Comment by bmeldal** [comment]
Yes, you are right, and we came up with short descriptions above! Short term memory...
Let's look at this next week, too.

**Comment by sandraorchard** [comment]
Read the top of this thread, the suggestions are all in there.
