### ISSUE TITLE
EMDB xrefs

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#38]
As subsection of "Properties" underneath litemol viewer

They are also 3D structures but I don't think we have a way of showing their visualisation - yet. There is a viewer on their pages.

**Comment by tschaka1904** [comment]
Do you have an example complex?

**Comment by bmeldal** [comment]
Sorry, here's one (a big one!):
http://www.ebi.ac.uk/intact/complex/details/EBI-9696567

**Comment by tschaka1904** [comment]
![screen shot 2017-03-30 at 16 24 09](https://cloud.githubusercontent.com/assets/5269116/24512035/5e351d3c-1565-11e7-8d58-c782e46f1da1.png)

**Comment by tschaka1904** [comment]
Maybe we can pull in some more data?

**Comment by tschaka1904** [comment]
Also the url is broken.

**Comment by bmeldal** [comment]
Example should point here:
http://www.ebi.ac.uk/pdbe/entry/emdb/EMD-2635
Another issue with the search url in the OBO file???

**Comment by tschaka1904** [comment]
Currently it points to: [http://www.pdbe.org/emd-EMD-2635](http://www.pdbe.org/emd-EMD-2635)

**Comment by bmeldal** [comment]
Yup, that's the search url in the editor, too.
Let's look at that with Pablo as he'll have to change the OBO file. He's on holiday next week, right???

**Comment by tschaka1904** [comment]
Hi @pporrasebi could you please have a look to this URL issue?

**Comment by pporrasebi** [comment]
Hi, current search regex for EMDB is http://www.pdbe.org/${ac}. Did they change it recently again? I am not sure if I can update the CVs fully from here (probably I can do it for the github version, but not for the sourceforge one).

**Comment by bmeldal** [comment]
They must have changed it again. Don't you love anything that's 'stable'???
If you can't update then we'll have to live with (or rather 'without'!) it until you are back.

**Comment by pporrasebi** [comment]
I'll give it a try, let's see where I get.

**Comment by pporrasebi** [comment]
OK, issue fixed in the github version of the CV. Let me know if it goes through and actually fixes your problem.

**Comment by bmeldal** [comment]
Thanks, Pablo. Fingers crossed...

**Comment by pporrasebi** [comment]
Currently xref points to https://www.ebi.ac.uk/complexportal/www.ebi.ac.uk/pdbe/entry/emdb/2635, so there is an error in the way the xref is formed. The PSI-MI CV entry is fine, this comes from the website level. Please @elisabetb have a look.
