### ISSUE TITLE
Search Box

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#42]
...isn't really a "box". I know it's the new guidelines box but may be worth feeding back to Ken et all that it doesn't really work in practice. Henning feels the same (see his email).

**Comment by tschaka1904** [comment]
This has been discussed with the guidelines committee and the results can be seen here: https://ebiwd.github.io/EBI-Pattern-library/patterns/search/

**Comment by tschaka1904** [comment]
I need to update the current CP to make the changes visible. But, this design suggests that we have no big 'Examples'-box. As they are shown directly underneath of the search-box. I know that you may think that this is not visible enough, but this is a global pattern and everyone is going to implement it this way.

**Comment by bmeldal** [comment]
We'll just have to run with it and add the extended examples to the HELP page. But this makes unique complex IDs even more important :)

And the search BOX is back!!! :)
