### ISSUE TITLE
ORCID IDs to acknowledge curators

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#44]
Could acknowledge the individual curator as Reactome do (and link to their orcid IDs)

[from Henning], +1 from me

**Comment by tschaka1904** [comment]
I'm not sure about this, but I have my doubts that we can do that out of the box. We would need to store the orcid IDs in our database first. ..I guess. 

/cc @noedelta @git4anjali

**Comment by bmeldal** [comment]
I wouldn't prioritise this right now but crediting curators via Orcid is the way forward so we should start putting this in place longterm. I know Sandra is in contact with the Literature team who are speadheading this for EBI in general.

**Comment by bmeldal** [comment]
This will be handled by new implementations spear-headed by the literature group.
