### ISSUE TITLE
Add 'copy this AC' button to header 

### ISSUE THREAD

**Issue by tschaka1904** [Complex-Portal/complex-portal-view#47]
This is a suggestion in issue #46. Similar behaviour as OLS.

**Comment by tschaka1904** [comment]
We will https://clipboardjs.com for that.

**Comment by tschaka1904** [comment]
This goes hand in hand with the `CPX-1235678` ids. Once they are in place, we can add this feature.

**Comment by bmeldal** [comment]
Was never requested by users, not commonly found in other DBs. Closing as not essential and more important features take priority.
