### ISSUE TITLE
event calling of participants in different viewers

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#48]
We discussed making the participants table, ComplexViewer and ChordViewer interactive, The LightMol viewer can also call a single chain and highlight it.

When you look at the event calling feature, please consider that feature, too. You might have to ask the pdbe devs :)

Thanks,
Birgit

**Comment by tschaka1904** [comment]
We need to have a idea how to display first. A mockup would be good. 

/cc @noedelta @git4anjali @sandraorchard @pporrasebi

**Comment by bmeldal** [comment]
Moved to Jira:
https://intact.atlassian.net/browse/CP-243
