### ISSUE TITLE
open unique hit directly on details page

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#49]
If user searches for an AC that has a unique hit the details page should open automatically. I know Henning mentioned this before as well.

E.g. 
EBI-xxxxxx complex AC (or new complex ACs)
AC in xrefs, such as a PDB or Chembl AC...

If AC is primary AC for a complex and also appears in the xrefs as an < inferred-from > - what to do? Would people expect the unique complex to open or would they like to see the related complex that is inferred from it?

Birgit

**Comment by tschaka1904** [comment]
Just to double check. When you search for [EBI-1202920](https://complex-portal.github.io/complex-portal-view/search?query=EBI-1202920&page=1), you'll get 3 results. I guess that these Complexes are somehow linked to each other(?). 

Despite the other two Complexes we still want to go directly to EBI-1202920?

**Comment by tschaka1904** [comment]
I don't know. This is why I personally think that this could confuse the user. 

@sandraorchard what do you think?

**Comment by tschaka1904** [comment]
This needs definitely a proper strategy.

**Comment by bmeldal** [comment]
We should also speak to Sangya. She would have tested the behaviour in Uniprot. I think I'm supposed to meet up with her soon. I'll send her a message.

**Comment by tschaka1904** [comment]
@bmeldal Did you speak to Sangya about this?

**Comment by bmeldal** [comment]
Yes, almost forgot.

She suggested to open the unique result directly but only if the user searches with the CP ACs (not for a text term or Uniprot AC...). If the CP AC is also in the xref (e.g. human AC in mouse entry as xref) display the search results as the evidence might be in mouse but the user wants human.

**Comment by tschaka1904** [comment]
I'll have a look and see how that performs. Current WS implementation might not be as smooth.

**Comment by bmeldal** [comment]
Let's try and test it :)

**Comment by tschaka1904** [comment]
Okay this needs some work on the WS. Otherwise the back-button is not working as normal. ...and we don't want a second editor.

**Comment by bmeldal** [comment]
We definitely want the back button ;-)

We can park this for the next version if it's too time consuming.

**Comment by bmeldal** [comment]
We are not going to do this anyway until we have the new CPX CAs. On @noedelta's list :)

**Comment by bmeldal** [comment]
No-one complained in 1.5 years, closing it.
