### ISSUE TITLE
PTM features

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#50]
These have a column in the old table (other features) but are now lost in the new view.

In the long term they could go on the Chord viewer. We have no bright idea where to but them in the current complex view :(

We have few examples so it would be good to highlight them where we have them!
E.g. http://www.ebi.ac.uk/intact/complex/details/EBI-9692430

**Comment by tschaka1904** [comment]
Also this needs some thinking how to display it. 

/cc @sandraorchard @pporrasebi @git4anjali @noedelta

**Comment by bmeldal** [comment]
This will form part of InVar and OTAR-48
