### ISSUE TITLE
Superfluous headings

### ISSUE THREAD

**Issue by sandraorchard** [Complex-Portal/complex-portal-view#55]
Can heading disappear when we have no associated data e.g. Diseases and Pathologies - we actually only have human data for this, as far as I am aware, but its visible and obviously empty for every species. It would look better if invisible.

**Comment by tschaka1904** [comment]
Thanks for pointing it out. We either make it grey or make it invisible. The current behaviour is more a bug.

**Comment by sandraorchard** [comment]
I'd go invisible - for some entries we'd otherwise end up with a long list of grey headings

**Comment by bmeldal** [comment]
agree with Sandra
