### ISSUE TITLE
EFO url is broken

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#57]
The url for orphanet/EFO ACs doesn't work any more:

Orphanet:46532 in

https://complex-portal.github.io/complex-portal-view/complex/EBI-9008420

should point to

http://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_46532

or

EFO:0000685 in https://complex-portal.github.io/complex-portal-view/complex/EBI-9992716

should point to

http://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000685

It's not just that the search url is wrong, the colon ":" needs changing to an underscore "_" as well. Looks like ols have changed the url - again...

Have fun :)
Birgit

**Comment by pporrasebi** [comment]
Fixed search URLs to comply with new OLS specifications. Also fixed ChEMBL target search url and PSI-MI alongside.

**Comment by pporrasebi** [comment]
Please check in a week's time or so, once OLS has sync'ed with the latest version of our CV, and close ticket if everything looks fine.

**Comment by tschaka1904** [comment]
We need to clone the database prod to test. This should solve this.
