### ISSUE TITLE
ComplexViewer superfamilies and Uniprot features don't work

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#58]
request to load above features doesn't load as external site doesn't support https

**Comment by tschaka1904** [comment]
Yes. This is because they don't support https and GitHub is only allowing https-requests. Basically the same issue we had with reactome. 

I've contacted both groups and asked about https. Once the CP is running on an EBI server this won't be a problem.

**Comment by bmeldal** [comment]
Thanks. Everyone knows it's a dev version so I won't get shot down for it :)
