### ISSUE TITLE
species name for yeast

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#62]
shows up as "yeast" but should be full scientific name: Saccharomyces cerevisiae strain xxxx

Probably getting it from the wrong field...

**Comment by tschaka1904** [comment]
Please provide example AC in future tickets. ...makes it easier for me to check the issue. ;-) 

Same on old CP: http://wwwdev.ebi.ac.uk/intact/complex/details/EBI-9682603

**Comment by bmeldal** [comment]
Sorry, usually put in ACs.

It used to show the scientific name. Something changes in the DB we are querying?

**Comment by tschaka1904** [comment]
I just double checked in the editor. 
![screen shot 2017-03-24 at 11 22 57](https://cloud.githubusercontent.com/assets/5269116/24292220/47749e5a-1084-11e7-9f40-12ca642a22a5.png)

I guess you need to change the full name?

**Comment by bmeldal** [comment]
Strange. Will check after football. Only on my phone in Pebbles btw a meeting and the game! See you after lunch.

**Comment by bmeldal** [comment]
We changed the full name to Saccharomyces cerevisiae in the Editor. Will update with next release.
