### ISSUE TITLE
Query string missing

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#63]
What are we going to do about the query string on the results page? For short queried, such as the GO term query or a simple CQL string it would be helpful to be reminded what one was searching for. Or will it be in the box in the header that's still to come?

**Comment by tschaka1904** [comment]
It will be in the search box in the header.

**Comment by tschaka1904** [comment]
The search box can be also a bit bigger.

**Comment by tschaka1904** [comment]
Will be solved with issue #2
