### ISSUE TITLE
ECO

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#67]
Please change "Evidence Code Ontology" to "Evidence and Conclusion Ontology  (ECO)" in the <about> page. It was just pointed out to me by the ECO PI who's here :) (and appreciated me mentioning ECO in the talk!)

**Comment by tschaka1904** [comment]
Sure no problem. Do display ECOs already? I don't think I have brought them in yet.

**Comment by bmeldal** [comment]
Marcus looked at the GH page but clicked through to the <about>page which is on the old site.

So, yes to both, Full Name for ECO needs changing on (new) <about> page and and ECO code on details page is not yet on GH but in the xref table on the old page.

He made a few other remarks, like code missing on new page and adding logo to our home page (to be discussed with Sandra.)

Anyway, what are you doing checking GH tickets at 11pm on a Sunday night? Nothing better to do?

**Comment by tschaka1904** [comment]
I see! Feedback is always good. 

Haha! ...I just checked if someone from the States checked out the new CP ;-)

**Comment by tschaka1904** [comment]
This relates to #33

**Comment by bmeldal** [comment]
Did they check it out? There must have been a bit of a spike after my talk.

**Comment by tschaka1904** [comment]
![screen shot 2017-03-27 at 14 38 59](https://cloud.githubusercontent.com/assets/5269116/24359114/44f11392-12fb-11e7-80e2-f81d008cf883.png)

There is a spike!

**Comment by bmeldal** [comment]
Fantastic! All your hard work is paying off. We are on the final straight :)
