### ISSUE TITLE
Contributors ribbon

### ISSUE THREAD

**Issue by tschaka1904** [Complex-Portal/complex-portal-view#70]
Here is the current version of the list of Contributors:
![screen shot 2017-03-30 at 14 08 43](https://cloud.githubusercontent.com/assets/5269116/24505654/986e20ec-1552-11e7-9e74-6184c66fdd67.png)

Have we forgotten anyone? Do we need to reorder them?

**Comment by tschaka1904** [comment]
What do you thing @sandraorchard & @bmeldal?

**Comment by bmeldal** [comment]
Can't see there being a 'right' order so maybe just alphabetically?

**Comment by tschaka1904** [comment]
This would look like this: 
![screen shot 2017-03-30 at 16 36 33](https://cloud.githubusercontent.com/assets/5269116/24512648/133ce9b6-1567-11e7-9c37-ff8d50f36cb2.png)

**Comment by bmeldal** [comment]
Wait for @sandraorchard to comment.

**Comment by sandraorchard** [comment]
Alphabetically is OK, its the one thing no-one can argue with
