### ISSUE TITLE
Header spaces

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#73]
We need a white line above the major header section. There is one below the headers!

**Comment by tschaka1904** [comment]
Could you please describe what you mean with 'white line'?

**Comment by bmeldal** [comment]
A line of white space so there's a visual indication that a new section starts. The bit Henning dislikes but I just spoke to Sangya and the lack of spacing was her first comment! So that's already 2 of us...

**Comment by tschaka1904** [comment]
The section headers or the local header?

**Comment by bmeldal** [comment]
Section headers, the green-ish ones. There seems to be space around the grey headers.

**Comment by tschaka1904** [comment]
There is also space around the others, but as it seems not enough. On the top or on the bottom?

**Comment by bmeldal** [comment]
On top/above - whichever way you want to describe it. Below seem to be enough space.

Most extreme example of the 'no space' issue is between LiteMol viewer and Expression header.

**Comment by tschaka1904** [comment]
## Before: 
![screen shot 2017-04-05 at 10 56 41](https://cloud.githubusercontent.com/assets/5269116/24700348/cd9289ca-19ee-11e7-82b4-4aedd94ab67a.png)

## After: 
![screen shot 2017-04-05 at 10 55 50](https://cloud.githubusercontent.com/assets/5269116/24700374/dbfd1cdc-19ee-11e7-93de-4b40aa44080c.png)

What do you think?

**Comment by bmeldal** [comment]
Better, but I would increase the space a bit more, maybe another 50%. Compare the space btw "3D structure" and the Litemol viewer and the viewer and "Expression".
