### ISSUE TITLE
Update to current and new pages

### ISSUE THREAD

**Issue by sandraorchard** [Complex-Portal/complex-portal-view#79]
We are saying nothing about ComplexTab or XML3.0 on our website so can we change the text on http://www.ebi.ac.uk/intact/complex/download/

FROM:

Complex Portal is released monthly and all data is in PSI-MI 2.5 format. See the PSI website for a detailed format description.

All Complex Portal data and software is freely available to all users, academic or commercial, under the terms of the Apache License, Version 2.0, from ftp://ftp.ebi.ac.uk/pub/databases/intact/complex/current/

TO:

The Complex Portal is released monthly and data on individual complexes is available for download in both PSI-MI XML2.5 and XML3.0 formats (see the PSI website for a detailed format  description). The files are grouped by species. We have now also developed ComplexTAB, a flatfile format to enable simpler parsing or loading into Microsoft Excel. A separate ComplexTAB file has been produced for each species - details on the format are available here  (ftp://ftp.ebi.ac.uk/pub/databases/intact/complex/current/complextab/README.htm). All files are available from the ftp site (ftp://ftp.ebi.ac.uk/pub/databases/intact/complex/current/) and will be updated as we add new complexes with every data release.

All Complex Portal data and software is freely available to all users, academic or commercial, under the terms of the Apache License, Version 2.0

**Comment by bmeldal** [comment]
@tschaka1904 has a new version for the help and about menus which includes all the formats but looks like it's not yet deployed on GH. We were working on that before you left for China.

**Comment by bmeldal** [comment]
I take that back: Go to < download> tile:
https://complex-portal.github.io/complex-portal-view/download
It's all there!

**Comment by bmeldal** [comment]
Well, you added a bit more text but the links are all there.

And yes, no "readme" file in complexTAB folder.

**Comment by sandraorchard** [comment]
The Complex Portal is released monthly and data on individual complexes is available for download in both PSI-MI XML2.5 and XML3.0 formats . We have now also developed ComplexTAB, a flatfile format to enable simpler parsing or loading into Microsoft Excel. A separate ComplexTAB file has been produced for each species - details on the format are available here (ftp://ftp.ebi.ac.uk/pub/databases/intact/complex/current/complextab/README.htm). All files are available from the ftp site (ftp://ftp.ebi.ac.uk/pub/databases/intact/complex/current/) and will be updated as we add new complexes with every data release. We also make available an MI-JSON download for web visualisation.

Link for PSI-MI XML2.5 = https://github.com/MICommunity/psimi/blob/wiki/PsimiXMLSpecifications.md
Link for PSI-MI XML3.0 = https://rawgit.com/MICommunity/psidev/master/psi/mi/rel30/doc/MIF300.html
JAMI=https://github.com/MICommunity/psi-jami

**Comment by bmeldal** [comment]
Suggestions for slight changes:

The Complex Portal is released monthly and data on individual complexes is available for download in both PSI-MI XML2.5 and XML3.0 formats. We recommend using XML3.0 as it contains more detailed annotations.

We provide ComplexTAB, a tsv flatfile format, to enable simpler parsing or loading into speedsheets. A separate ComplexTAB file is produced for each species - details on the format are available here (ftp://ftp.ebi.ac.uk/pub/databases/intact/complex/current/complextab/README.htm). 

All XML and ComplexTAB files are available from the ftp site (ftp://ftp.ebi.ac.uk/pub/databases/intact/complex/current/) and are updated with every data release. 

We provide MI-JSON files for web visualisation of individual complexes via the webservice (https://wwwdev.ebi.ac.uk/intact/complex-ws/), each Complex Details page (e.g. https://complex-portal.github.io/complex-portal-view/complex/EBI-9008420) and the Basket (https://complex-portal.github.io/complex-portal-view/basket).

**Comment by bmeldal** [comment]
The latest suggestions have not yet been added.

I can't re-open the ticket (don't have the button).
