### ISSUE TITLE
Ontologies section

### ISSUE THREAD

**Issue by tschaka1904** [Complex-Portal/complex-portal-view#80]
As currently displayed on the homepage, we want to provide a ontology section. For starters we want to implement the `ols-aotocomplete`, which would allow us to search trough an ontology. 

Currently, the `ols-aotocomplete`, has some errors which need to be fixed. I've contacted the developer and hope for a quick and easy fix. It is basically about how they deal with their dependencies, as the `ols-aotocomplete` doesn't bring any of these in.

**Comment by bmeldal** [comment]
I thought it was just the GO ontology, not the whole OLS?
@sandraorchard

**Comment by sandraorchard** [comment]
You need to access the ontology, whichever one it is - and using a generic OLS approach means we can then move to additional CVs such as ChEBI

**Comment by tschaka1904** [comment]
Yes, we can define which ontology we would like to use.

**Comment by bmeldal** [comment]
Ok, that all sounds good :)

**Comment by tschaka1904** [comment]
We're waiting for OLS to fix a bundling issue with their tool.

**Comment by tschaka1904** [comment]
This was mentioned in #112

**Comment by tschaka1904** [comment]
It seems like there is not much happening on the OLS side... I can either spend more time to make their tool working with us, develop my own version of it or we leave it for now? 

The problem is basically they way how they bundle the module and that they are not bundling all the dependencies with it.

**Comment by bmeldal** [comment]
We'll have to sit down and think about options. In any case, GO terms can be used as search terms directly in the search box.

**Comment by bmeldal** [comment]
Moved to Jira:
https://intact.atlassian.net/browse/CP-241
