### ISSUE TITLE
What to capture with GoogleAnalytics?

### ISSUE THREAD

**Issue by tschaka1904** [Complex-Portal/complex-portal-view#82]
We're almost there and I'm just creating all the events we want to capture with GA. Here is my list:

Homepage: 
- [x] Which search term has been entered 
- [x] Search on enter or search-button
- [x] Which tile has been clicked

Header: 
- [ ] Which tab has been clicked (Documentation, About, Basket, Feedback, Logo for home-button)

Download page: 
- [x] Which download tile/type has been clicked

Organsims: 
- [x] Which organisms has been clicked (search or download(format))

Results:
- [x]  Which filter has been applied 
- [x]  Usage of navigation trough the results (pagination)

Details: 
- [ ] User interacts with InteractionViewer (very simple, but basically if the user clicks on it)
- [x] Which buttons from InteractionViewer have been clicked (Enlarge, Reset, etc.)
- [ ] User clicks on external link
- [x] User interacts with Reactome diagram (same as InteractionViewer)
- [ ] User interacts with GXA diagram (same as InteractionViewer & Reactome diagram)
- [x] User clicks on JSON view button
- [x] User clicks on download button
- [x] Usage of side menu

Basket:
- [x] Which complex has been added to basket
- [x] Which complex has been deleted from basket

Please feel free to extend or change this list. 

@bmeldal @sandraorchard

**Comment by sandraorchard** [comment]
I assume the basics such as country of origin are covered. Can we distinguish between academic (edu ac) and other be distinguished.
Length of time on each page
Number of searches per session

**Comment by tschaka1904** [comment]
This is all stuff already captured by default.

**Comment by bmeldal** [comment]
Homepage:
- [x] Clicks on other links, e.g which examples are used or whether they have subscribed to the newsletter.


All sub-pages:
- [x] Capture if they continued by using the search box in the header

Details:
- [x] User clicks on basket button

Basket:
- [x] also which download option they chose
