### ISSUE TITLE
Apache license = CC-?

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#83]
Is there an equivalent to the open source license codes that start with CC-xx for The Apache 2.0 license? Is it CC0?

A lot of people asking about the CC license codes so would be great if we could state it in these terms, too.

https://en.wikipedia.org/wiki/Creative_Commons_license

**Comment by tschaka1904** [comment]
Creative Commons license and Apache 2.0 license are two different licenses .
