### ISSUE TITLE
Evidence by... not working

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#84]
clicking on the link open the front page of OLS but needs to open the specific page for that ECO code. I can now see a flaw in our way of summarising several codes under one verbal heading unless the specific code is still embedded in the background.

**Comment by tschaka1904** [comment]
This is because the url is wrong in the WS. Need correction in the database: 
![screen shot 2017-05-19 at 11 16 27](https://cloud.githubusercontent.com/assets/5269116/26243715/b4e1e3fe-3c84-11e7-9ce8-d2934e630dab.png)

**Comment by tschaka1904** [comment]
Should be: http://www.ebi.ac.uk/ols/ontologies/ECO/terms?obo_id=ECO:0000353

**Comment by bmeldal** [comment]
Does that need changing on the ontology file?
Has this changed to due OLS changing their search urls?

**Comment by tschaka1904** [comment]
Yes it need changing in the ontology file. I don't think that this is related to any OLS changes, because it looks like a very old style URL.

**Comment by bmeldal** [comment]
Ok, one to check with @pporrasebi on Monday.

**Comment by tschaka1904** [comment]
This is not a issue for the CP anymore. I'll close this ticket here.
