### ISSUE TITLE
PDB codes

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#85]
https://complex-portal.github.io/complex-portal-view/complex/EBI-1209326

has only got one link to PDB and it looks 'lost'; nothing happens when you click on it as the structure is already displayed. It looks like a bug when it isn't.

Solution: add a heading for that column:
"Structures available in The PDB"
It also now occurs to me that we don't provide a link out to PDBe directly!

**Comment by tschaka1904** [comment]
No we don't provide a link. It was never made as an requirement or documented in any mockup. 

I'll add the heading

**Comment by bmeldal** [comment]
I know, it only just occurred to me! We have the link outs in the Reactome and GXA widgets and the direct links in all other places but nothing to link directly to PDBe.

**Comment by tschaka1904** [comment]
I'll add a little PDBe logo there with the outgoing-url icon.

**Comment by tschaka1904** [comment]
![screen shot 2017-05-19 at 16 27 45](https://cloud.githubusercontent.com/assets/5269116/26254996/363afadc-3cb0-11e7-8b73-9cb12b7be869.png)


Is this okay?

**Comment by bmeldal** [comment]
Looks good :)
