### ISSUE TITLE
GXA widget

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#86]
I don't think it loads at all now. Is the link broken due to their new release?

I tried PCNA and Hemoglobin examples.

**Comment by tschaka1904** [comment]
This might be due the release they did yesterday.

**Comment by tschaka1904** [comment]
Yes. It seems like they have done something to their `wwwdev`. Using `www` solves the issue.

**Comment by bmeldal** [comment]
We know they've done something to wwwdev, we discussed it on Tuesday :) It needs a new configuration...

**Comment by tschaka1904** [comment]
Yes and no. I've changed all of that, but their `wwwdev` doesn't work at the moment. Doesn't matter, because they have released the new version of the gxa viewer on `prod` and this one works.
