### ISSUE TITLE
MatrixDB & Signor links

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#87]
We are still missing these.

Add under < names and publications >?
If yes, we need to re-name that section to < additional information > and add a section: < other databases > or something like that.

**Comment by tschaka1904** [comment]
I don't think that I pull them in yet. Do we need another Section? @bmeldal @sandraorchard

**Comment by sandraorchard** [comment]
Rather  than another section, do as suggested above. Retitle the Names and Publications  section to "Additional Information" 
Retitle 'Additional Reading' as 'Further Reading' - just to use a different phrase
Then put MatrixDB under a new heading 'External resources' - we may think of a better heading but it will do for now.

**Comment by tschaka1904** [comment]
Do we have an example with MatrixDB & Signor links?

**Comment by tschaka1904** [comment]
I've renamed the headers. Just waiting for the example now.

**Comment by bmeldal** [comment]
only 1 Signor complex that I could find:
http://www.ebi.ac.uk/intact/complex/details/EBI-11619951
search: signor-c*

one of many MatrixDB complexes:
http://www.ebi.ac.uk/intact/complex/details/EBI-2554508
search: MULT_*

**Comment by tschaka1904** [comment]
signor URL is wrong. Currently points to:
http://signor.uniroma2.it/RelationServlet?id=SIGNOR-C100/

but should point to:
http://signor.uniroma2.it/relation_result.php?id=SIGNOR-C100&organism=human

**Comment by bmeldal** [comment]
@pporrasebi, can we update that in the OBO file, please?

**Comment by tschaka1904** [comment]
This is not a issue for the CP anymore. I'll close this ticket here.
