### ISSUE TITLE
CQL syntax not on new site

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#88]
We need to add the table with CQL styntax until we can offer the jquery for the CP :)

**Comment by tschaka1904** [comment]
This goes here: https://complex-portal.github.io/complex-portal-view/documentation/query_syntax

**Comment by tschaka1904** [comment]
Kind of references #77

**Comment by bmeldal** [comment]
Yes, that's the right place for it. I wasn't sure if we missed it or if it was still on some other list. I didn't want to forget about it after I went through the training materials with Hema so quickly opened a ticket :)

I think we are also missing the "search hints" from the old help page, like using boolean operators and asterix as wildcards to include isoforms.

**Comment by tschaka1904** [comment]
We need to revisit the structure of the CQL page. There are lists and sentences and I'm not sure how to combine them the best. With the list I'd like to do something like this: 
![screen shot 2017-06-16 at 15 17 33](https://user-images.githubusercontent.com/5269116/27230492-5b640206-52a7-11e7-93bf-334aa75d081d.png)
But I'm not sure what to do with the sentences, as you can see in the picture.

**Comment by bmeldal** [comment]
Moved to Jira:
https://intact.atlassian.net/browse/CP-227
