### ISSUE TITLE
Training tile

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#91]
The training tile currently points to the IntAct training page and there is nothing on there. Are we waiting for the training team to provide a widget that auto-updates? If not we have to re-populate that page before Max moves the CP to Prod :)

@sandraorchard

**Comment by tschaka1904** [comment]
> Are we waiting for the training team to provide a widget that auto-updates?
They don't really have that, but I think we can ask for page. Something like: www.ebi.ac.uk/training/complexportal. ...But we need to request that.

**Comment by tschaka1904** [comment]
I've sent an email to WebDev and wait for their response now.

**Comment by tschaka1904** [comment]
I'll meet Joseph on Monday afternoon to discuss the new MI training page.

**Comment by tschaka1904** [comment]
I've met with Joseph and he will provide in the near future a JSON, which we can use to filter out our relevant events.

**Comment by bmeldal** [comment]
Moved to Jira:
https://intact.atlassian.net/browse/CP-240
