### ISSUE TITLE
Request complex tile

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#92]
Feedback from Ian Barrett (AZ):
Maybe call it "Request complex for curation" to clarify what it does.

PS: We also had comments in the survey to provide a form behind this tile.

**Comment by tschaka1904** [comment]
What do you mean by 

> We also had comments in the survey to provide a form behind this tile.

We link to: https://www.ebi.ac.uk/support/intact

**Comment by bmeldal** [comment]
A proper form for them so they can fill the relevant fields I need :) I have a word doc that I have shared with our regular requesters.

**Comment by tschaka1904** [comment]
This should still go over the `EBI SUPPORT & FEEDBACK`-System. Maybe you can talk to systems if they can make another form for you. We agreed at the retreat that we should 'always' use the `https://www.ebi.ac.uk/support/{{service}}` form.

**Comment by bmeldal** [comment]
Who do I talk to in Systems? I wonder if other services already use a form.

**Comment by tschaka1904** [comment]
I'm not sure. Maybe use the tsc portal: http://tsc.ebi.ac.uk/help

**Comment by tschaka1904** [comment]
I'll close that issue, as I've changed the name of the tile and the rest doesn't depend on the CP.
