### ISSUE TITLE
context-dependent help

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#93]
We might want to think about context-dependent help options for each section.

This might help us guide users to undiscoverable functionalities, esp in the ComplexViewer.

**Comment by tschaka1904** [comment]
This needs some discussion, what and when we want to tell the user something. 
But this is how it could look like: 
![shift](https://cloud.githubusercontent.com/assets/5269116/26686977/80c35dac-46e6-11e7-9899-9e626f075259.png)

**Comment by bmeldal** [comment]
Definitely takes some discussion, just didn't want to forget!

**Comment by tschaka1904** [comment]
We should have a meeting about this and go through the pages and define the help notifications. ...also we need to discuss if the 'help-boxes' are visible enough? 

/cc @sandraorchard @pporrasebi

**Comment by bmeldal** [comment]
Some thoughts from user testing with Neera (21/6/17):
The drop-down menu provides all 4 options even when there's no data, e.g. our good friend Hemoglobin has no binding regions or superfamily info so the circles stay white and the user wonders if they have done something wrong as they expect some action when making a selection. - Should those options be greyed out?

**Comment by bmeldal** [comment]
Features have been improved!
