### ISSUE TITLE
Protein names in viewer

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#95]
Loose the _species as the complexes are all species-specific.

**Comment by tschaka1904** [comment]
I think this is rather an issue for the [ComplexViewer](https://github.com/MICommunity/ComplexViewer)

**Comment by bmeldal** [comment]
No, as the ComplexViewer can also be used for mix-species cases in other applications! We need to strip it at our end (if we can).

**Comment by tschaka1904** [comment]
Okay, this is then either the new WS or in the editor. But I guess the name is pulled in from UniProt?

**Comment by bmeldal** [comment]
At the moment, yes, protein_name from UniProt. Could change this to gene_name...

**Comment by colin-combe** [comment]
@tschaka1904 - yes, its not an issue for ComplexViewer - the viewer just displays whatever is in the label attribute. Its an issue for whatever generates the data sent (JAMI?)

**Comment by bmeldal** [comment]
Thanks, Colin. We'll look at this from our side, then.

**Comment by tschaka1904** [comment]
It's going to be the new WS then! ;-)

**Comment by bmeldal** [comment]
Just a comment: Today we looked at a complex that has all UniProt PRO chains and the user got really confused as she knows the complex well but never heard of the PRO chains. She'd also expect gene names in the display (it was fine in the table though).

**Comment by bmeldal** [comment]
Also see: https://intact.atlassian.net/projects/CP/issues/CP-30
Can we display only the short label for the binding regions, not the type = "binding-associated region"? The latter could confuse users as it's a DB thing, not biology.

**Comment by colin-combe** [comment]
I think previous comment:
>Can we display only the short label for the binding regions

is one for ComplexViewer.

I have changed it and merged it into MICommunity repo (but not released it). You can check a demo at complexviewer.org .  Does it seem right?

I also changed the colour scale annotation colours are taken from. Although I a big fan of the colorbrewer scales, some of the colours are a bit light for use on a white background. Changed the default colorbrewer scheme used to one free of this problem. Do you think its better?

**Comment by bmeldal** [comment]
Thanks, @colin-combe. Looks good. Apologies for the late reply but was on holiday :)
@tschaka1904 thanks for deploying latest version :)

**Comment by bmeldal** [comment]
Looks all done.
