### ISSUE TITLE
subsets for crystals not indicated

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#96]
Using LiteMol we no longer indicate if a PDB xref is to the complete structure or a partial complex. Do we need to bring that back? Eventually, this will be solved by PDBe's 'best structure' algorithm but they are not there yet.

@sandraorchard

**Comment by tschaka1904** [comment]
Is this a bug?

**Comment by bmeldal** [comment]
No, not a bug. We use the qualifier=subset or =identity in the editor to indicate if the structure contains all complex participants or just some but while designing the new page we forgot to take that into consideration. The old page had that as a column in the xref table which we got rid off! 

Needs a bit of thought to come up with a clean solution. Maybe make something different about the button that selects the structure for display in LiteMol. Hatched background if subset? It will need a small legend below the list as well.

**Comment by bmeldal** [comment]
Will be covered by new PDBe-CP pipeline.
