### ISSUE TITLE
Single item result list

### ISSUE THREAD

**Issue by hHermjakob** [Complex-Portal/complex-portal-view#98]
Whenever a query returns only a single item result list, that item should be displayed directly, rather than the single item list.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search existing issues for a similar problems/requests
[ ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**

**Expected behaviour**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behaviour?**

**Please tell us about your environment:**

**Comment by tschaka1904** [comment]
This is a duplicate to #49

**Comment by bmeldal** [comment]
duplication of #49
