### ISSUE TITLE
Scrolling behaviour

### ISSUE THREAD

**Issue by hHermjakob** [Complex-Portal/complex-portal-view#99]
When I'm in the complex view, I scroll down (Using two finger swiping on the Mac trackpad. 
As soon as I get into the Reactome pathway viewer, it swallows my scrolling and turns it into zoom level change. 
If I did out of that trap, the same happens two cm further down when I get into the 3d viewer.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search existing issues for a similar problems/requests
[ ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**

**Expected behaviour**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behaviour?**

**Please tell us about your environment:**

**Comment by bmeldal** [comment]
We know. And we have some ideas about how to handle it. If you have any suggestions please fire away :)

(It happens when navigating with the mouse, too.)

**Comment by tschaka1904** [comment]
We've tried to allow to navigate in the Diagramm only on click, but this didn't feel right. @noedelta, @git4anjali and I had a long conversation about it, but couldn't find 'the' solution. We're hopping to get some ideas/feedback in this round of testing.

**Comment by tschaka1904** [comment]
Reactome developers have changed the scrolling behaviour and this should solve this issue. Please give it a try and your feedback would be much appreciated! 👍

**Comment by bmeldal** [comment]
@hHermjakob did you check the new version? Scrolling worked during testing yesterday. 

Then we can close the ticket :)

**Comment by tschaka1904** [comment]
I'm still working together with the guys who develop the LiteMol viewer to make it work the same. ..also I've contacted Colin, because his viewer is not scrollable on mobile.

**Comment by bmeldal** [comment]
ComplexViewer scrolling ticket:
https://github.com/MICommunity/ComplexViewer/issues/113

**Comment by tschaka1904** [comment]
Okay. I was in contact with the developer of the LiteMol viewer and we have found a bug in the latest version. Basically he has updated to the latest version on React (a Framework, similar to Angular), but no it stops working in some cases. He in investigating into it, he said.

**Comment by tschaka1904** [comment]
This bug has now been resolved and the ListMol viewer also is now scrolling friendly too! 👍

**Comment by bmeldal** [comment]
Got stuck again in LiteMol during testing today, Chrome for Mac with touchpad only.

Can't reopen :(
